### ISSUE TITLE
Segmentation fault when trying to load from io.StringIO

### ISSUE THREAD

**Issue by josch** [pygraphviz/pygraphviz#101]
Hi,

I thought that pygraphviz was able to read graphs from file-like objects because this works:

```
python3 -c 'import sys,io,pygraphviz;pygraphviz.AGraph(file=open("foo.dot"))'
```

Or from a handle to standard input:

```
python3 -c 'import sys,pygraphviz;pygraphviz.AGraph(file=sys.stdin)' < foo.dot
```

But this throws a segmentation fault:

```
python3 -c 'import sys,io,pygraphviz;pygraphviz.AGraph(file=io.StringIO(sys.stdin.read()))' < foo.dot
```

And so does this:

```
python3 -c 'import sys,io,pygraphviz;pygraphviz.AGraph(file=io.StringIO(open("foo.dot").read()))'
```

I want to use `io.StringIO` because I have my graph as a Python string and I want to avoid having to write it into a temporary file before I can parse it with pygraphviz.

Could you fix the segmentation fault or show me another way to read dot data from a Python string I only have in memory?

Thanks!

**Comment by dschult** [comment]
This looks like a problem with your installed io.StringIO
Have you been able to use it without pygraphviz?
Your description makes it look like it is not a pygraphviz issue.

**Comment by josch** [comment]
Hi @dschult this sounds as if you cannot reproduce the behaviour I observe?

If it is a problem with my installed io.StringIO then it is a problem with Python 3 in Debian unstable. I would gladly file a bug if you could give me a pointer about what you mean by being "able to use it without pygraphviz"? The following for example works fine:

    $ python3 -c "import io;i=io.StringIO('foobar');print(i.read())"
    foobar

**Comment by dschult** [comment]
You can pass a string directly to AGraph.
Try this?
python3 -c 'import sys,io,pygraphviz;pygraphviz.AGraph(open("foo.dot").read())'

**Comment by josch** [comment]
What about my io.StringIO question? Are you able to reproduce it as well or not?

Passing the file data to `AGraph` like this is a bad idea. This will either lead to some input graphs not be recognized as such (because the regex is not precise enough) or it will lead to some filenames be intepreted as graph data (because they happen to match the regex). The advantage of accepting a file-like object to pass graph data is, that a file-like object can be unambiguously be distinguished from a file path (a simple Python string).

Though I now see that the `AGraph` interface changed and that there is now a `string` argument which seems to not try to interpret the string I give it as a filename but just as dot data.

It then seems that I must make another bug report against networkx which uses `Agraph` with the (apparently deprecated) `file` argument and doesn't try to use the `string` or `filename` argument as required.

It would still be good to throw an exception instead of letting the segmentation fault happen though.

**Comment by dschult** [comment]
I am able to reproduce the segmentation fault when using io.StringIO.

So, I think a fix for you is to just give the string to AGraph instead of forcing a file interface to the string.  

Meanwhile it would be good to figure out how/where the segmentation fault is occurring and either fix it or raise an exception instead.
Thanks for bringing this.

**Comment by hagberg** [comment]
Yes, send the dot string data to AGraph using the string= argument.

The dot file reader can take open file handle or a filename (which is then opened).   Since io.StringIO is neither of those it breaks.  The file is read by graphviz's c-code parser which doesn't know about Python's io.StringIO.

**Comment by hagberg** [comment]
This should be re-opened as "Handle reads using Python file objects" and figure out how to do that properly with libcgraph.
