### ISSUE TITLE
pygraphviz installation issue

### ISSUE THREAD

**Issue by alfpohl** [pygraphviz/pygraphviz#105]
Hi all,
I try to install pygraphviz on windows and get some error messages.
I know that there are some other discussion topics describing a similar issue, but so far I don´t got a solution.

My Environment:
Windows 7 (64-Bit), python 2.7, Visual C++ for Python 2.7, graphviz-2.38, pygraphviz-1.3.1.
graphviz-2.38 has been installed in the standard directory: C:\Program Files (x86)\Graphviz2.38

I´ve  performed the install for pygraphviz as follows:
python setup.py install
(from the pygraphviz root directory).

(output)
running install
include_dirs=None
library_dirs=None
running build
running build_py
running egg_info
writing pygraphviz.egg-info\PKG-INFO
writing top-level names to pygraphviz.egg-info\top_level.txt
writing dependency_links to pygraphviz.egg-info\dependency_links.txt
reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc\build'
writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
running build_ext
building 'pygraphviz._graphviz' extension
C:\Users\pohl\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\
VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -INone -Ic:\python27\include
-Ic:\python27\PC /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win32-2.7\Release\p
ygraphviz/graphviz_wrap.obj
graphviz_wrap.c
pygraphviz/graphviz_wrap.c(2954) : fatal error C1083: Cannot open include file:
'graphviz/cgraph.h': No such file or directory
error: command 'C:\\Users\\pohl\\AppData\\Local\\Programs\\Common\\Microsoft\\Vi
sual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

As you can see above, the include file cgraph.h is not found. As the include_dirs and library_dirs are currently not set, I tried to set them in the setup.py file in line 38+39 as suggested in other blogs.

library_dirs='C:/Program Files (x86)/Graphviz2.38/lib/release/lib'
include_dirs='C:/Program Files (x86)/Graphviz2.38/include'

However, the include_dirs and libraby_dirs variables are still set to None when executing the install
with the modified setup.py. The missing file exists in the Graphviz2.38 directory, but the install is not finding it.

Any comment or answer is appreciated.

regards
Alfred

**Comment by hagberg** [comment]
It looks like you have asked to look for the cgraph.h file at 
C:/Program Files (x86)/Graphviz2.38/include/graphviz/cgraph.h

We reworked some of the setup code (there is now setup.py and setup_extra.py where the paths are set).  Maybe try downloading the current development version, set those paths and see if it works?

**Comment by hagberg** [comment]
See https://github.com/pygraphviz/pygraphviz/issues/103#issuecomment-258568238
