### ISSUE TITLE
hello  everyone!      how to use    port and position of record in pygraphviz ?

### ISSUE THREAD

**Issue by caiyuntayue** [pygraphviz/pygraphviz#106]
when add edge
G.add_edge('node0:n','node1.n')
G.add_edge('node2.f3','node1.f1')

G.string() get 
        node6    [label="<f1>23|<f3>\ ",    shape=record];
        "node0:f1" -> "node1:f2";
        "node2:f3" -> "node1:f1";

"" added

the other problem

and how to connect to self ?

**Comment by hagberg** [comment]
Your question isn't clear.    Please post the code with your error.
