### ISSUE TITLE
pygraphviz

### ISSUE THREAD

**Issue by hynek2001** [pygraphviz/pygraphviz#107]
Hi,
i love graphviz. but i have issue with getting it working on windows 10 64bit. i spent quite lot time with testing ,and with various combination. but i failed.  issue is , graphviz is distributed as 32bit, and i am not able to compile it ... and none link i found on windows or in anaconda works on windows 10 64bit( i tryed compile with 32bit python & 64bit python, with lib & include corectly set...)

so here is request for enhacment. can you please distribute compiled version for windows 10 64 bit to anaconda?

**Comment by mraky** [comment]
i was digging around, and i found howto compile it... and i wanted to ask you for advise.

i found workround from Kagami 
https://github.com/Kagami/pygraphviz/commit/fe442dc16accb629c3feaf157af75f67ccabbd6e
but his fork is for python 2.x   

therefore i forked last pygraphviz    to https://github.com/mraky/pygraphviz , & apply  Kagami's workaround  , and then i could compile pygrapviz on windows10 :)


now what is my question - do you think it is possible to add Kagami changes to pygraphviz/pygraphviz   ?
