### ISSUE TITLE
Incorrect number of edges on graphviz 2.40.1

### ISSUE THREAD

**Issue by lucaswiman** [pygraphviz/pygraphviz#111]
I found a bug in rendering of multigraphs when run against graphviz version 2.40.1, but not against graphviz version 2.38.0.

I've reduced this down the minimal code to reproduce below. The joint causes seem to be:
- Use of a newer version of graphviz.
- Use of the `key` kwarg. The graph renders properly when the `key` kwarg is omitted on both 2.40.1 and 2.38.0.  Unfortunately, the parameter is passed by networkx when rendering the graph in my case, so I don't have much control over it.

### Code to reproduce Graphviz==2.40.1
```python
>>> import os
>>> import pygraphviz
>>> 
>>> A = pygraphviz.AGraph(strict=False, directed=True)
>>> 
>>> A.add_node('a')
>>> A.add_node('b')
>>> 
>>> A.add_edge('a','b', key='0')
>>> A.add_edge('a','b', key='1')
>>> 
>>> print(len(A.edges(keys=True)))
1
>>> assert len(A.edges(keys=True)) == 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> 
>>> os.system('rm /tmp/foo.dot /tmp/foo.png')
0
>>> A.write('/tmp/foo.dot')
>>> os.system('dot -Tpng /tmp/foo.dot -o /tmp/foo.png')
0
>>> os.system('open /tmp/foo.png')
0
```

The rendered PNG looks like this:
![foo](https://cloud.githubusercontent.com/assets/123110/21739782/449f45ce-d45a-11e6-888e-906693b41218.png)

### Same code works correctly graphviz==2.38.0
```python
>>> import os
>>> import pygraphviz
>>> 
>>> A = pygraphviz.AGraph(strict=False, directed=True)
>>> 
>>> A.add_node('a')
>>> A.add_node('b')
>>> 
>>> A.add_edge('a','b', key='0')
>>> A.add_edge('a','b', key='1')
>>> 
>>> print(len(A.edges(keys=True)))
2
>>> assert len(A.edges(keys=True)) == 2
>>> os.system('rm /tmp/foo.dot /tmp/foo.png')
0
>>> A.write('/tmp/foo.dot')
>>> os.system('dot -Tpng /tmp/foo.dot -o /tmp/foo.png')
0
>>> os.system('open /tmp/foo.png')
0

```
The rendered PNG looks like this:
![foo](https://cloud.githubusercontent.com/assets/123110/21739773/e67679d6-d459-11e6-85b3-14bd5b274202.png)

<hr>

### Appendix: Development setup

All tests were done on with the following setup:
- Python 3.5
- OS X 10.11.6
- graphviz installed via homebrew
- `pygraphviz==1.3.1` (I also confirmed the issue still occurs on the HEAD of this library.)

The latest graphviz can be installed by running `brew install graphviz || brew upgrade graphviz`

The slightly older version of graphviz (which works on this example) can be installed by running:
```
brew uninstall graphviz
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
git checkout a5307ebabb4d969ae851737ef19a77425565441e Formula/graphviz.rb # graphviz-2.38.0_1.el_capitan
brew install graphviz  
```

Now `brew list --versions | grep graphviz` should show `graphviz 2.38.0_1`.

## Thanks!

Please let me know if you need more information. For the time being, downgrading graphviz seems to be a reasonable workaround.  

**Thanks for writing this library!** It's proven really useful in an algorithmic visualization I'm working on, and the integration with `networkx` is really slick!

**Comment by hagberg** [comment]
I can reproduce the failure with graphviz-2.40.1.  I was unable to build the development version of graphviz but that might be a good next step in case this was a bug in graphviz that is now fixed.

**Comment by lucaswiman** [comment]
That's a great idea. I just looked into trying to build it by hand inside a docker container. The build process takes a while, but once I get a build setup that reproduces the bug, I can run `git bisect run` on it to pinpoint the issue.

I got graphviz to build and install, but I'm struggling with getting pygraphviz to find the library. My attempts to do this are described here: https://gist.github.com/lucaswiman/1f73a8371b1fe81a58f5dc7374f3b3b2

Any ideas on how to fix that `CalledProcessError`? I tried applying the patch from #108 but it didn't fix it.

**Comment by lucaswiman** [comment]
Phew, finally got it working once I forced it to find the right library path using this diff:
```
diff --git a/setup_extra.py b/setup_extra.py
index d50ceca..03082a7 100644
--- a/setup_extra.py
+++ b/setup_extra.py
@@ -58,6 +58,8 @@ def _dpkg_config():
                 break
     except OSError:
         print("Failed to find dpkg")
+    except S.CalledProcessError:
+        print("Could not run dpkg")
     return include_dirs, library_dirs
 
 
@@ -129,8 +131,8 @@ def get_graphviz_dirs():
     # You must set both 'library_dirs' and 'include_dirs'
 
     # Linux, generic UNIX
-    #library_dirs='/usr/lib/graphviz'
-    #include_dirs='/usr/include/graphviz'
+    library_dirs='/usr/local/lib/graphviz'
+    include_dirs='/usr/local/include/graphviz'
 
     # OSX, Linux, alternate location
     #library_dirs='/usr/local/lib/graphviz'
```
and ran the command not from the [source directory](https://groups.google.com/d/msg/pygraphviz-discuss/FgypPFy1bNE/tQ-YaWSxUzYJ).

Happily, it does seem that this bug is fixed on the graphviz development version! The example in the issue description generated the following nice graph:
<img width="99" alt="screen shot 2017-02-12 at 9 26 16 pm" src="https://cloud.githubusercontent.com/assets/123110/22871889/f1a24060-f169-11e6-9432-f3c8db61106c.png">

I'm closing this issue, since it seems to be fixed upstream. Thanks for looking into it, and apologies for the trouble!
