### ISSUE TITLE
Empty AGraph.graph_attr object

### ISSUE THREAD

**Issue by fedarko** [pygraphviz/pygraphviz#113]
Hi --
First off, thanks for pygraphviz. It's been very helpful in my work.

As a bit of background for this issue: I use pygraphviz in my code by creating a string in the DOT language representing a digraph and using it as the `string` parameter to initialize an `AGraph` object. I then lay out the nodes, edges, and subgraphs of the graph (using `.layout(prog="dot")`), after which I retrieve the graph's bounding box using `.graph_attr[u'bb']`. Then I iterate through the subgraphs, edges, and nodes within the digraph, storing their position information from the layout operation. This entire process is often repeated within my code multiple (potentially hundreds or thousands) of times with different graphs.

I've noticed that occasionally, while repeating this process for different graphs, a graph will have a `graph_attr` object of `{}` even after calling `layout` on the graph. This is a problem, since I need to record the bounding box of the graph. Sometimes, also, I get a segmentation fault when trying to print a `graph_attr` object.

I think the [issue detailed here](https://groups.google.com/forum/#!msg/pygraphviz-discuss/CkMHrCUln1Q/pT3aBDtJBAAJ) may be related to this. The issue persists even when I call `.clear()` and `.close()` on the graph every time I finish storing data from it (before I would reinitialize the graph with a new DOT string).

This isn't a pressing issue to me, as I can work around it to extract bounding boxes in other ways. However, I thought it might be a good idea to file an issue if other people have also faced this problem.

Thanks!

**Comment by hagberg** [comment]
I can't reproduce this with the code you point to.  If you have a repeatable error please to post the code here so we can investigate.

**Comment by fedarko** [comment]
Thank you for your response. I've prepared a very trimmed-down version of my code that exhibits an error (specifically, the segmentation fault error I mentioned in the first post -- I haven't had the time to replicate the empty graph_attr error yet, due to recent changes in my codebase), and am including it in this post.

In practice, the error seems to arise with different graphs at different times -- however, the enclosed graph seems to always trigger the error in this particular context, at least on my system.

A number of factors seem to influence whether or not PyGraphViz has a segfault for this particular code snippet. Changing all or one of the node names that start with `"cluster_"` to start with `"c_"` instead seems to fix the problem, but so does changing pretty much any line (node, edge, graph property) within the DOT string. Also, as is mentioned in the code, adding a print statement after obtaining the bounding box  seems to also fix the problem (something to do with threading/etc., maybe?)

(The node names that start with `"cluster_"` are an idiosyncrasy resulting from the way I lay out graphs in my application. To my knowledge GraphViz doesn't treat node names that start with `"cluster_"` specially, but I could be wrong. I encountered these sorts of errors even before using node names that started with `"cluster_"`.)

For reference, I'm running Debian 8.6 x86_64, using Python 2.7.9 and PyGraphViz 1.3.1. While running this code within the [fish shell](https://fishshell.com/), I get the error `fish: "./pgv_test.py" terminated by signal SIGSEGV (Address boundary error)`, and when I run this code within bash I just get a `Segmentation fault` message.

```python
#!/usr/bin/env python
# exhibits the error described here --
# https://github.com/pygraphviz/pygraphviz/issues/113
import pygraphviz
gv_input = """digraph asm {
	xdotversion=1.7;
	node [fixedsize=true];
	edge [headport=n,tailport=s];
	cluster_B12620_7813_9438_2566 [height=9.58333,width=5.80556,shape=rectangle];
	cluster_C5437_3721 [height=6.52778,width=3.05556,shape=rectangle];
	6203 [height=2.91275,width=2.91275,shape=invhouse];
	6859 [height=2.87448,width=2.87448,shape=invhouse];
	12207 [height=4.60568,width=4.60568,shape=invhouse];
	18519 [height=2.37107,width=2.37107,shape=invhouse];
	12613 [height=2.61384,width=2.61384,shape=invhouse];
	cluster_B12620_7813_9438_2566 -> 6203 [comment="2566,6203"]
	cluster_B12620_7813_9438_2566 -> 18519 [comment="2566,18519"]
	6203 -> 6859 [comment="6203,6859"]
	6203 -> 18519 [comment="6203,18519"]
	6859 -> cluster_C5437_3721 [comment="6859,5437"]
	12207 -> cluster_C5437_3721 [comment="12207,5437"]
	12613 -> cluster_B12620_7813_9438_2566 [comment="12613,12620"]
}"""
i = 1
while True:
    # Ideally, this would run forever (the same graph would be created and
    # then destroyed over and over again). However, that is not the case.
    h = pygraphviz.AGraph(gv_input)
    h.layout(prog='dot')
    print "hi"
    # This next step is what causes errors
    bb = h.graph_attr[u'bb']
    # Interestingly, adding a print statement after accessing bb seems to
    # prevent the segfault. Uncomment the below line to observe this.
    #print "bye"

    h.clear()
    h.close()
    i += 1
```

Hope this helps. Again, thanks for your help with this.

**Comment by hagberg** [comment]
I tested this on my setup and it works fine (runs for as long as I let it).  
I'm using different versions of probably everything so not much help in tracking this down.
$ dot -V
dot - graphviz version 2.40.1 (20161225.0304)
Might be the difference?  I'm also using Python3
$ python3 
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux

**Comment by fedarko** [comment]
Ah, I was using Python 2.7.9 and GraphViz version 2.38.0 previously.

I updated my version of GraphViz to 2.40.1 (the exact same version as yours, according to `dot -V`). To see if the python version made a difference, I also installed Python 3.4.3 and the Python3 version of pygraphviz on my system. Here are the results from running the script on my system with the new GraphViz version in the two different python environments:

#### In Python 2.7.9, with GraphViz 2.40.1
It seems like the "segfault" error doesn't happen any more when running the given code, but I'm still getting an error of `KeyError: 'agattr: no key'` the first time line 32 of the script is reached (since `h.graph_attr` is empty).
#### In Python 3.4.3, with GraphViz 2.40.1
The script runs for much longer than it does in Python 2.7.9 before crashing, but (sometimes after just a few seconds, sometimes after about a full minute of it running) it will still crash due to the aforementioned `KeyError`. I still am not sure at this point why this behavior is exhibited; perhaps some sort of memory leak somewhere?

As before, the behavior of the script is highly variable depending on what seems like minutiae. Using `print(h.graph_attr)` in lieu of line 30, for example, immediately causes a segmentation fault in Python 2.7.9 but seems to work fine in Python 3.4.3 (at least until the script crashes at line 32 later).

**Comment by toddagibson** [comment]
I stumbled on this thread for my similar experience. The test code above segfaults reliably for me. This is on both a docker ubuntu container running on OS X, and on Arch Linux running natively on a server. On Arch, Python 3.6.1 & dot 2.40.1. In the container both are slightly older.

Interestingly, the above code segfaults even if I precede the graph_attr call with h.write("file.dot"). Despite file.dot containing the bb information, the subsequent call to graph_attr segfaults. The only way I can prevent the above code from segfaulting is by hitting it over the head with its own dot file:

```
  h = pygraphviz.AGraph(gv_input)

  h.layout(prog='dot')

  h.write("file.dot")

  h=pygraphviz.AGraph("file.dot")

  print "hi"

  # This next step is what causes errors

  bb = h.graph_attr[u'bb']
```

On my own code, behavior vacillates between working, KeyError, and segfault.
