### ISSUE TITLE
undefined symbol: Agundirected

### ISSUE THREAD

**Issue by ghost** [pygraphviz/pygraphviz#115]
Hi,
I am new to python and after installing pygraphviz (after a real-struggle), I try running  >>> import pygraphviz as pgv and gives me this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/pygraphviz/_graphviz.so: undefined symbol: Agundirected

I have seen some solution like the one of #71  but it didn't work for me, it seems.
After executing  $pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"

I get is this: 
/usr/local/lib/python2.7/dist-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Requirement already satisfied: pygraphviz in /usr/local/lib/python2.7/dist-packages

And then too import pygraphviz as pgv doesn't work.

**Comment by hagberg** [comment]
This looks like it might be a bad installation of graphviz?   Can you provide details on which versions you are using?

**Comment by ljsjl** [comment]
Hi, I've run into this too. In my case it's Python 3.4, Ubuntu 14.04 with bundled graphviz(-dev), 2.36.0-0ubuntu3.2. Not a huge issue for me as I can work around it but the additional info might help you pin down the cause.

**Comment by brchiu** [comment]
I encountered this issue too.
I performed the following clean up before re-installing pygraphviz.
This procedure works for me. 

```
$ sudo pip2 uninstall pygraphviz -y
$ sudo rm -rf /usr/lib/python2.7/dist-packages/pygraphviz
$ sudo rm -f /usr/lib/python2.7/dist-packages/pygraphviz-1.4rc1.egg-info/
$ sudo pip2 install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
```

**Comment by danielbrowne** [comment]
I have also been affected by this issue. Using the install-option params above also resolved the problem, but this is not a great solution.

**Comment by Perseus14** [comment]
Faced same issue here. Works on python2 as well as python3 on Ubuntu 16.04

**Comment by rossbar** [comment]
From the responses it seems like this issue was resolved for the original OS/Python/pygraphviz versions. Please see the [updated installation guide](https://pygraphviz.github.io/documentation/stable/install.html#install) for recommendations on how to install the latest version of pygraphviz on Linux.

I you have are having problems installing, please open a new issue with info about your specific platform and how Graphviz was installed.
