### ISSUE TITLE
Installing pygraphviz on Windows 7 x64 for Python 3.5 x32 failing with fatal error LNK1120: 1  unresolved externals

### ISSUE THREAD

**Issue by 1001QAdotNET** [pygraphviz/pygraphviz#116]
Hi guys

I have read as much as I could about thjis but I am stuck and am not making any progress. I have tried to apply a patch as recommended in on the threads around here but that failed.
I am installing from source, downloaded from Github

Here is my command line

c:\Users\MyName\Downloads\pygraphviz\pygraphviz-master>C:\Users\MyName\AppData\L
ocal\Programs\Python\Python35-32\python.exe setup.py install --include-path "C:\
Program Files (x86)\Graphviz2.38\include" --library-path "C:\Program Files (x86)
\Graphviz2.38\lib\release\lib" 

I am getting this error

```
......
graphviz_wrap.obj : error LNK2001: unresolved external symbol _PyIOBase_Type
build\lib.win32-3.5\pygraphviz\_graphviz.cp35-win32.pyd : fatal error LNK1120: 1
 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\
link.exe' failed with exit status 1120

```

Could anybody please please help me with this? I would hate to have to use a different python library for my  application

**Comment by mmoosstt** [comment]
Hi,

my problem looks quite similar, I am trying around with the following setup:
- Windows7
- Visual Studio Express 2010 
- Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 10:55:48) [MSC v.1600 32 bit (Intel)]
- pygraphviz-1.4rc1.zip

and this is the result, any ideas?

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:/PYTHON33/Tools/graphviz-2.38/include -IC:\PYTHON33\include -IC:\PYTHON33\include /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win32-3.3\Release\pygraphviz/graphviz_wrap.obj
graphviz_wrap.c
pygraphviz/graphviz_wrap.c(3354) : warning C4047: 'return': Anzahl der Dereferenzierungen bei 'int' und 'Agsym_t *' unterschiedlich
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:/PYTHON33/Tools/graphviz-2.38/lib/release/lib /LIBPATH:C:\PYTHON33\libs /LIBPATH:C:\PYTHON33\PCbuild cdt.lib cgraph.lib /EXPORT:PyInit__graphviz build\temp.win32-3.3\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib.win32-3.3\pygraphviz\_graphviz.pyd /IMPLIB:build\temp.win32-3.3\Release\pygraphviz\_graphviz.lib /MANIFESTFILE:build\temp.win32-3.3\Release\pygraphviz\_graphviz.pyd.manifest
   Bibliothek "build\temp.win32-3.3\Release\pygraphviz\_graphviz.lib" und Objekt "build\temp.win32-3.3\Release\pygraphviz\_graphviz.exp" werden erstellt.
graphviz_wrap.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_PyIOBase_Type" in Funktion "__wrap_agread".
build\lib.win32-3.3\pygraphviz\_graphviz.pyd : fatal error LNK1120: 1 nicht aufgelöste externe Verweise.

**Comment by zorkmark** [comment]
Same problem here.

- Windows 7
- MSBuild 14.0
- Miniconda Python 3.6 32-bit
- graphviz-2.38.msi

pip install --global-option=build_ext --global-option="-IC:\Program Files (x86)\Graphviz2.38\include" --global-option="-LC:\Program Files (x86)\Graphviz2.38\lib\release\lib" XXXX

Where the XXXX's I've tried are:

- pygraphviz   
- pygraphviz==1.3.1 (is default above)
- pygraphviz==1.3rc2
- pygraphviz==1.4rc1
- git+https://github.com/pygraphviz/pygraphviz.git

Always a similar result:

Collecting pygraphviz==1.3.1
  Using cached pygraphviz-1.3.1.zip
Skipping bdist_wheel for pygraphviz, due to binaries being disabled for it.
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz: started
    Running setup.py install for pygraphviz: finished with status 'error'
    Complete output from command C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dor\\AppData\\Local\\Temp\\pip-build-iut2nvan\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext "-IC:\Program Files (x86)\Graphviz2.38\include" "-LC:\Program Files (x86)\Graphviz2.38\lib\release\lib" install --record C:\Users\dor\AppData\Local\Temp\pip-28ef66bo-record\install-record.txt --single-version-externally-managed --compile:
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\pygraphviz
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Graphviz2.38\include" -IC:\ProgramData\Miniconda3\include -IC:\ProgramData\Miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win32-3.6\Release\pygraphviz/graphviz_wrap.obj
    graphviz_wrap.c
    pygraphviz/graphviz_wrap.c(3321): warning C4047: 'return': 'int' differs in levels of indirection from 'Agsym_t *'
    creating C:\Users\dor\AppData\Local\Temp\pip-build-iut2nvan\pygraphviz\build\lib.win32-3.6
    creating C:\Users\dor\AppData\Local\Temp\pip-build-iut2nvan\pygraphviz\build\lib.win32-3.6\pygraphviz
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files (x86)\Graphviz2.38\lib\release\lib" /LIBPATH:C:\ProgramData\Miniconda3\libs /LIBPATH:C:\ProgramData\Miniconda3\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86" cgraph.lib cdt.lib /EXPORT:PyInit__graphviz build\temp.win32-3.6\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib.win32-3.6\pygraphviz\_graphviz.cp36-win32.pyd /IMPLIB:build\temp.win32-3.6\Release\pygraphviz\_graphviz.cp36-win32.lib
       Creating library build\temp.win32-3.6\Release\pygraphviz\_graphviz.cp36-win32.lib and object build\temp.win32-3.6\Release\pygraphviz\_graphviz.cp36-win32.exp
    graphviz_wrap.obj : error LNK2001: unresolved external symbol _PyIOBase_Type
    build\lib.win32-3.6\pygraphviz\_graphviz.cp36-win32.pyd : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120

**Comment by PhilipBak** [comment]
- Windows10
- Microsoft Visual Studio 14.0
- Python 3.6.3 32bit
- pygraphviz-1.4rc1.zip
- graphviz-2.38.msi

And I set
            library_dirs=['C:\Program Files (x86)\Graphviz2.38\lib\\release\lib']
            include_dirs=['C:\Program Files (x86)\Graphviz2.38\include']
in setup.py

I got a similar error:

running install
include_dirs=None
library_dirs=None
running build
running build_py
running egg_info
writing pygraphviz.egg-info\PKG-INFO
writing dependency_links to pygraphviz.egg-info\dependency_links.txt
writing top-level names to pygraphviz.egg-info\top_level.txt
reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc\build'
writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
running build_ext
building 'pygraphviz._graphviz' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Graphviz2.38
\include" -IC:\Users\user-pc\AppData\Local\Programs\Python\Python36-32\include -IC:\Users\user-pc\AppData\Local\Programs\Python\Python36-32\
include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\
INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\
um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files
(x86)\Windows Kits\8.1\include\\winrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win32-3.6\Release\pygraphviz/graphviz_wrap.obj
graphviz_wrap.c
pygraphviz/graphviz_wrap.c(3321): warning C4047: 'return': 'int' differs in levels of indirection from 'Agsym_t *'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO
"/LIBPATH:C:\Program Files (x86)\Graphviz2.38\lib\release\lib" /LIBPATH:C:\Users\user-pc\AppData\Local\Programs\Python\Python36-32\libs /LIB
PATH:C:\Users\user-pc\AppData\Local\Programs\Python\Python36-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\
VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10
.0.10240.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\
8.1\lib\winv6.3\um\x86" cdt.lib cgraph.lib /EXPORT:PyInit__graphviz build\temp.win32-3.6\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib
.win32-3.6\pygraphviz\_graphviz.cp36-win32.pyd /IMPLIB:build\temp.win32-3.6\Release\pygraphviz\_graphviz.cp36-win32.lib
Creating library build\temp.win32-3.6\Release\pygraphviz_graphviz.cp36-win32.lib and object build\temp.win32-3.6\Release\pygraphviz_graphviz.cp36-win32.exp
graphviz_wrap.obj : error LNK2001: _PyIOBase_Type 외부 기호를 확인할 수 없습니다.
build\lib.win32-3.6\pygraphviz\_graphviz.cp36-win32.pyd : fatal error LNK1120: 1unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120
