### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by shirriff** [pygraphviz/pygraphviz#118]
I went to http://pygraphviz.github.io/documentation.html
The "pdf" links on the right give a 404 page:
http://pygraphviz.github.io/documentation/pygraphviz-1.4rc1/_downloads/pygraphviz_reference.pdf
http://pygraphviz.github.io/documentation/development/_downloads/pygraphviz_reference.pdf

**Comment by ricelid** [comment]
It also links to http://networkx.github.io/documentation/latest/tutorial/, which is also broken.

**Comment by hagberg** [comment]
The links should point to http://networkx.readthedocs.io/en/stable/examples/pygraphviz/

**Comment by dschult** [comment]
These missing links in pygraphviz documentation seem to be gone now.
