### ISSUE TITLE
Error Installing on Windows 10 with python 3.6.1

### ISSUE THREAD

**Issue by jamespharper** [pygraphviz/pygraphviz#121]
Tried installing pygraphviz via pip, easy_install and from github (shown below), but all ended with same error (see below).  Any ideas?

C:\Users\James Harper\Downloads\pygraphviz-master>python setup.py install --include-path=/usr/local/Cellar/graphviz/2.38.0/include/graphviz --library-path=/usr/local/Cellar/graphviz/2.38.0/lib
C:\Program Files (x86)\Python36-32\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '1.5.dev' to '1.5.dev0'
  normalized_version,
running install
running build
running build_py
running egg_info
writing pygraphviz.egg-info\PKG-INFO
writing dependency_links to pygraphviz.egg-info\dependency_links.txt
writing top-level names to pygraphviz.egg-info\top_level.txt
reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc\build'
writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
running build_ext
building 'pygraphviz._graphviz' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/local/Cellar/graphviz/2.38.0/include/graphviz "-IC:\Program Files (x86)\Python36-32\include" "-IC:\Program Files (x86)\Python36-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win32-3.6\Release\pygraphviz/graphviz_wrap.obj
graphviz_wrap.c
c:\program files (x86)\python36-32\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by rv816** [comment]
I have had similar issues on Windows 10 with Python 3.6

```
PS C:\Users\rvass> pip install pygraphviz --no-cache-dir
Collecting pygraphviz
  Downloading pygraphviz-1.3.1.zip (123kB)
    100% |████████████████████████████████| 133kB 1.9MB/s
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Us
ers\\rvass\\AppData\\Local\\Temp\\pip-build-gffddf_4\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);
code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\rvass\App
Data\Local\Temp\pip-6jqju79p-record\install-record.txt --single-version-externally-managed --compile:
    running install
    include_dirs=None
    library_dirs=None
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\agraph.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\release.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\version.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\__init__.py -> build\lib.win-amd64-3.6\pygraphviz
    creating build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    running egg_info
    writing pygraphviz.egg-info\PKG-INFO
    writing dependency_links to pygraphviz.egg-info\dependency_links.txt
    writing top-level names to pygraphviz.egg-info\top_level.txt
    reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc\build'
    writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
    copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.6\pygraphviz
    running build_ext
    building 'pygraphviz._graphviz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visu
alstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\rvass\\AppData\\Loc
al\\Temp\\pip-build-gffddf_4\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\
r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\rvass\AppData\Local\Temp\pip-6jqj
u79p-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\rvass
\AppData\Local\Temp\pip-build-gffddf_4\pygraphviz\
```

**Comment by RaviTeja262** [comment]
I am facing the same issue but with a different package (scrapy). i guess it has something to do with the windows environment rather than package specific issue.  Still haven't found a solution for this. Please update the comment if anyone can find a solution to the issue.

    building 'twisted.test.raiser' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\src\twisted
    creating build\temp.win-amd64-3.6\Release\src\twisted\test
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -IC:\Users\SPAR\Anaconda3\envs\py36\include -IC:\Users\SPAR\Anaconda3\envs\py36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" /Tcsrc/twisted/test/raiser.c /Fobuild\temp.win-amd64-3.6\Release\src/twisted/test/raiser.obj
    raiser.c
    c:\users\spar\anaconda3\envs\py36\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\SPAR\Anaconda3\envs\py36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SPAR\\AppData\\Local\\Temp\\pip-build-1r_c6ufi\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SPAR\AppData\Local\Temp\pip-ma7xf1px-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SPAR\AppData\Local\Temp\pip-build-1r_c6ufi\Twisted\

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
run cmd as administrator that should solve the problem

**Comment by LalithAravind** [comment]
Hi, 

I too facing the same issue after trying with  *#*graphviz-2.38_x64.tar.gz**.
I am using python3.5 , vc++  build tools 14.0

used both the option

python setup.py install --include-path="C:\graphviz-2.38_x64\include\graphviz" --library-path="C:\graphviz-2.38_x64\lib"

pip install pygraphviz --install-option="--include-path=C:\graphviz-2.38_x64\include\graphviz" --install-option="--library-path=C:\graphviz-2.38_x64\lib"

Collecting pygraphviz
  Using cached pygraphviz-1.3.1.zip
Skipping bdist_wheel for pygraphviz, due to binaries being disabled for it.
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command C:\Anaconda\envs\tensorflow\python.exe -u -c "i
mport setuptools, tokenize;__file__='C:\\Users\\411967\\AppData\\Local\\Temp\\pi
p-build-mg6mbv65\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file
__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, '
exec'))" install --record C:\Users\411967\AppData\Local\Temp\pip-lihxba97-record
\install-record.txt --single-version-externally-managed --compile "--include-pat
h=C:\New Folder\include\graphviz" "--library-path=C:\New Folder\lib":
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\pygraphviz
    copying pygraphviz\agraph.py -> build\lib.win-amd64-3.5\pygraphviz
    copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.5\pygraphviz
    copying pygraphviz\release.py -> build\lib.win-amd64-3.5\pygraphviz
    copying pygraphviz\version.py -> build\lib.win-amd64-3.5\pygraphviz
    copying pygraphviz\__init__.py -> build\lib.win-amd64-3.5\pygraphviz
    creating build\lib.win-amd64-3.5\pygraphviz\tests
    copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.5\pygraphviz\tests

    copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.5\pygra
phviz\tests
    copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3
.5\pygraphviz\tests
    copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.5\pygraphviz
\tests
    copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.5\pygraphv
iz\tests
    copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.5\
pygraphviz\tests
    copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.5\pygraphviz
\tests
    copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.5\pygraphviz\
tests
    copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.5\pygraphvi
z\tests
    copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.5\
pygraphviz\tests
    copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.5\pygrap
hviz\tests
    copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.5\pygraphvi
z\tests
    copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.5\pygraph
viz\tests
    copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.5\pygraphv
iz\tests
    copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.5\pygraphviz\t
ests
    running egg_info
    writing pygraphviz.egg-info\PKG-INFO
    writing top-level names to pygraphviz.egg-info\top_level.txt
    writing dependency_links to pygraphviz.egg-info\dependency_links.txt
    reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*~' found anywhere in distri
bution
    warning: no previously-included files matching '*.pyc' found anywhere in dis
tribution
    warning: no previously-included files matching '.svn' found anywhere in dist
ribution
    no previously-included directories found matching 'doc\build'
    writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
    copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.5\pygraphviz
    copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.5\pygraphviz
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\pygraphviz
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
/c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\New Folder\include\graphviz" -IC:\Anac
onda\envs\tensorflow\include -IC:\Anaconda\envs\tensorflow\include "-IC:\Program
 Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\
Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kit
s\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-I
C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcpygraphviz/graphviz_wr
ap.c /Fobuild\temp.win-amd64-3.5\Release\pygraphviz/graphviz_wrap.obj
    graphviz_wrap.c
    pygraphviz/graphviz_wrap.c(2954): fatal error C1083: Cannot open include fil
e: 'graphviz/cgraph.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\cl.exe' failed with exit status 2

_**## Please anyone provide the proper solution**_

**Comment by plash29** [comment]
Same Issue here:
Window 7 64 bit 
Python 3.5.4
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -Ic:\users\pankaj.thakur\appdata\local\programs\python\include -IC:\Users\pankaj.thakur\AppData\Local\Programs\Python\Python35\include -IC:\Users\pankaj.thakur\AppData\Local\Programs\Python\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcsrc/twisted/test/raiser.c /Fobuild\temp.win-amd64-3.5\Release\src/twisted/test/raiser.obj
    raiser.c
    c:\users\pankaj.thakur\appdata\local\programs\python\python35\include\pyconfig.h(243): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\pankaj.thakur\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\PANKAJ~1.THA\\AppData\\Local\\Temp\\pip-build-hxxflk4n\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PANKAJ~1.THA\AppData\Local\Temp\pip-71wwa7ak-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\pankaj.thakur\appdata\local\programs\python\include\site\python3.5\Twisted" failed with error code 1 in C:\Users\PANKAJ~1.THA\AppData\Local\Temp\pip-build-hxxflk4n\Twisted\

Is any one got solution

**Comment by AlterKater13** [comment]
I tried: pip install scrapy //on windows 10 (Version 1607)

I had problems with:
fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory

for me worked:
Alternative: Get the Visual C++ 2015 Build Tools instead. It doesn't come with Visual Studio and all the useless cruft but make sure you select the Windows 8.1 SDK during the install.

and I got the tip from here:
https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/

download link which I used:
http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by plash29** [comment]
but i am using window 7

**Comment by plash29** [comment]
Hello @AlterKater13  Thanks for reply, Its working fine now, By Select the Windows 8.1 SDK During install.

**Comment by gnot18** [comment]
now I'll switch to Linux for good..

**Comment by PrakashRaj37** [comment]
i'm also have the same problem.....

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\AARBOR~1\\AppData\\Local\\Temp\\pip-install-lavejou0\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\AARBOR~1\AppData\Local\Temp\pip-record-ptsziesz\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\AARBOR~1\AppData\Local\Temp\pip-install-lavejou0\pygraphviz\

Is anyone find solution???

**Comment by ligenxun** [comment]
error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    
    ----------------------------------------

Command "D:\MyPython\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ligen\\AppData\\Local\\Temp\\pycharm-packaging\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ligen\AppData\Local\Temp\pip-
record-21jq13fd\install-record.txt --single-version-externally-managed --compile --install-headers D:\MyPython\venv\include\site\python3.7\Twisted" failed with error code 1 in C:\Users\ligen\AppData\Local\Temp\pycharm-packaging\Twisted\

**Comment by LOL-XDD** [comment]
For a lot of modules you may need to specify the version number you want in order to actually install it. This is not a 100% guarenteed solution but it worked for me.

```
[X] pip install pywebview
[✓] pip install pywebview==2.0.3
```

You can find most version numbers on the Github page for the module you are installing.

**Comment by xai1983kbu** [comment]
I was trying to install Scrapy but had run into an error

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

then I've installed Twisted (it's needed for Scrapy) from https://www.lfd.uci.edu/~go...
and Scrapy was successfully installed.

**Comment by Laowai01** [comment]
Add window 10 and window 8.1 sdk to your environment path

**Comment by Icogerard** [comment]
@belov38  - Muchísimas gracias. 
1. Descargue el fichero directo del enlace que proporcionaste.
2. Instale Twisted directo del archivo. Sin problemas, como mencionaste.
      pip install Twisted-18.7.0-cp37-cp37m-win_amd64.whl
3. Instale "Channels". (Para instalar "channels", es necesario instalar "twisted")
     pip install -U channels 
Todo esto, lo tengo por mi parte dentro de un entorno virtual generado con Anaconda.
Saludos cordiales a todos!

**Comment by pankajsharma120** [comment]
try to install with anconda, this fixed my error - `conda install -c conda-forge scrapy`

**Comment by Duanxh2018** [comment]
> i'm also have the same problem.....
> 
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe' failed with exit status 2
> 
> ```
> ----------------------------------------
> ```
> Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;**file**='C:\Users\AARBOR1\AppData\Local\Temp\pip-install-lavejou0\pygraphviz\setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record C:\Users\AARBOR1\AppData\Local\Temp\pip-record-ptsziesz\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\AARBOR~1\AppData\Local\Temp\pip-install-lavejou0\pygraphviz\
> 
> i'm using windows10
> Is anyone find solution???

I met the same problem, and how you solved?

**Comment by nlderek** [comment]
I face the same problem when I try to pip install pyAudio

fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

**Comment by anishgop** [comment]
same error .. when i tried to install pyAudio
c:\users\agopinath\appdata\local\continuum\anaconda3\include\pyconfig.h(117): note: command-line arguments:  see previous definition of 'MS_WIN64'
    src/_portaudiomodule.c(29): fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by anishgop** [comment]
> I face the same problem when I try to pip install pyAudio
> 
> fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\HostX86\x86\cl.exe' failed with exit status 2


suggestion:
portaudio is not a Python package, it's a C library that's entirely independent of Python, so you can't install it via pip.

conda config --add channels conda-forge 
then install conda install pyaudio

**Comment by Maitreya29** [comment]
> try to install with anconda, this fixed my error - `conda install -c conda-forge scrapy`

You're a legend. Been trying to fix it since two days and your reply fixed it. This also works for other packages :)

**Comment by johnthagen** [comment]
It would be really amazing if official binary wheels were provided for Windows on PyPI.

**Comment by ashimahorra** [comment]
Facing the same error while installing cytoolz. error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Tried installing twisted. Have already installed visual studio build tools. Error still persists.

**Comment by pleavinseven** [comment]
> suggestion:
> portaudio is not a Python package, it's a C library that's entirely independent of Python, so you can't install it via pip.

Would this work through a virtual environment? If the module is already installed locally should it be easier to install in the venv?

**Comment by rossbar** [comment]
The issues reported here installing pygraphviz on windows should be fixed in pygraphviz v1.7 which was just released. Please see the [updated installation docs](https://pygraphviz.github.io/documentation/stable/install.html#windows) for details.

Since this a long thread with a lot of info, if you are still having trouble installing pygraphviz on Windows please open a new issue with info on how Graphviz was installed on your system.

**Comment by connelblack** [comment]
> I face the same problem when I try to pip install pyAudio
> 
> fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\HostX86\x86\cl.exe' failed with exit status 2

have you got the solution

**Comment by Petros626** [comment]
> 
> 
> ```
> error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
> 
> ----------------------------------------
> ```
> 
> Command "D:\MyPython\venv\Scripts\python.exe -u -c "import setuptools, tokenize;**file**='C:\Users\ligen\AppData\Local\Temp\pycharm-packaging\Twisted\setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record C:\Users\ligen\AppData\Local\Temp\pip-
> record-21jq13fd\install-record.txt --single-version-externally-managed --compile --install-headers D:\MyPython\venv\include\site\python3.7\Twisted" failed with error code 1 in C:\Users\ligen\AppData\Local\Temp\pycharm-packaging\Twisted\
> 
> the same problem。。when i pip install scrapy
> anyone help me T^T
> 
> 2018-09-08 22:29:57
> i solved the problem , my [Twisted] error，download the file (https://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted) ,and install it ,when it success,try [pip install scrapy] again,it works

which versions :) ?

**Comment by Petros626** [comment]
> 
> 
> Tried installing pygraphviz via pip, easy_install and from github (shown below), but all ended with same error (see below). Any ideas?
> 
> C:\Users\James Harper\Downloads\pygraphviz-master>python setup.py install --include-path=/usr/local/Cellar/graphviz/2.38.0/include/graphviz --library-path=/usr/local/Cellar/graphviz/2.38.0/lib
> C:\Program Files (x86)\Python36-32\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '1.5.dev' to '1.5.dev0'
> normalized_version,
> running install
> running build
> running build_py
> running egg_info
> writing pygraphviz.egg-info\PKG-INFO
> writing dependency_links to pygraphviz.egg-info\dependency_links.txt
> writing top-level names to pygraphviz.egg-info\top_level.txt
> reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '_~' found anywhere in distribution warning: no previously-included files matching '_.pyc' found anywhere in distribution
> warning: no previously-included files matching '.svn' found anywhere in distribution
> no previously-included directories found matching 'doc\build'
> writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
> running build_ext
> building 'pygraphviz._graphviz' extension
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/local/Cellar/graphviz/2.38.0/include/graphviz "-IC:\Program Files (x86)\Python36-32\include" "-IC:\Program Files (x86)\Python36-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win32-3.6\Release\pygraphviz/graphviz_wrap.obj
> graphviz_wrap.c
> c:\program files (x86)\python36-32\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe' failed with exit status 2

hey:)

in my case i have this message with double backslashes ? its weird isnt it?
