### ISSUE TITLE
how to apply html feature to the attr "label" of nodes like graphviz

### ISSUE THREAD

**Issue by lchkeepit** [pygraphviz/pygraphviz#122]
for example, we can code as following:
graph{
1   [margin=0 shape=box, style=filled, fillcolor=white, color=green, label=html];
 }
thx!

**Comment by hagberg** [comment]
It's the same as using graphviz.  See the examples here
https://github.com/pygraphviz/pygraphviz/blob/master/pygraphviz/tests/test_html.py
