### ISSUE TITLE
Locating graphviz executables in windows (anaconda) is broken

### ISSUE THREAD

**Issue by MarkVanDerVoort** [pygraphviz/pygraphviz#135]
On Windows 10, when installing using Anaconda access to the graphviz executables is wrapped by a series of batch files. 

PyGraphviz cannot find these batch files (it looks for the extension .exe only) and reports the graphviz executables missing.

This is due to the implementation of _which. Could this be replaced with a call to shutil.which. This implementation takes the multiple windows extension into account.

This is both the case for Python 2.7 as 3.4. I know that currently Anaconda only has backports for 2.7.
If needed I can create a pull request, but I'd like your opinion first (me being rather new to python)

**Comment by lpinner** [comment]
@MarkVanDerVoort I just came to report this also.  I'm working around by monkey patching `pygraphviz.agraph.AGraph._which`


    try:
        from shutil import which
    except ImportError:
        try:
            from backports.shutil_which import which
        except ImportError:
            which = shutil_which

    #Monkey patch pygraphviz.agraph.AGraph._which
    def _which(self, name):
        return which(name)

    def shutil_which(cmd, mode=os.F_OK | os.X_OK, path=None):
        # Code from shutil.which
        # https://github.com/python/cpython/blob/master/Lib/shutil.py#L1096
        # PYTHON SOFTWARE FOUNDATION LICENSE VERSION 2

And in calling scripts:

    import pygraphviz.agraph
    pygraphviz.agraph.AGraph._which = _which

**Comment by hagberg** [comment]
PR welcome.  I don't have a windows OS to test.

**Comment by rossbar** [comment]
At the time of this posting, there are still issues with outdated graphviz+pygraphviz packages on Anaconda: see #326 .

Pygraphviz 1.7 was just released though, which should make installing pygraphviz on Windows via pip much easier. Please see the [updated installation instructions](https://pygraphviz.github.io/documentation/stable/install.html#windows) for details.

I'm going to close this as it has been inactive for a while, but if problems persist or you have trouble with the non-conda install, please feel free to re-open with the latest info.
