### ISSUE TITLE
module 'pygraphviz' has no attribute 'AGraph'

### ISSUE THREAD

**Issue by cquennouelle** [pygraphviz/pygraphviz#142]
Hi,

After having met several difficulties to install pygraphviz, I've managed to do it using the git clone procedure and using the following command:
``sudo python setup.py install``

However, I'm now facing another problem when trying to execute the example:

``>>> import pygraphviz as pgv``
``>>> G = pgv.AGraph()``
``---------------------------------------------------------------------------``
``AttributeError                            Traceback (most recent call last)``
``<ipython-input-2-b0c2138e6702> in <module>()``
``----> 1 G = pgv.AGraph()``
`` ``
``AttributeError: module 'pygraphviz' has no attribute `'AGraph'` ``

Did someone already solved this one ? 
Thank you for your help.

**Comment by cquennouelle** [comment]
OK, this seems to be partially resolved, since I mixed up my python versions.

**Comment by DIUANA** [comment]
HI I am facing this issue. May you share the solution?

**Comment by cquennouelle** [comment]
This was quite a long time ago, but if I remember correctly, I had a confusion between 'pip install ...' and 'pip3 install ...' since I was running both Python2 and Python3 on my computer.
Sorry to not be more specific.
