### ISSUE TITLE
pygraphviz fails on AppVeyor (Windows)

### ISSUE THREAD

**Issue by diegozea** [pygraphviz/pygraphviz#150]
Hi,

I'm trying to use AppVeyor to test a Python package that depends on pygraphviz on Windows.
I can install it using `pip` if I indicate the path to graphviz using `--install-option`. However, I cannot get a working `pygraphviz`. I get the following error:
```
c:\python27\lib\site-packages\pygraphviz\graphviz.py:24: in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
E   ImportError: DLL load failed: The specified module could not be found.
```
The full output is here: https://ci.appveyor.com/project/diegozea/phylosofs-fku85/build/1.0.31
My configuration file for AppVeyor is this: https://github.com/PhyloSofS-Team/PhyloSofS/blob/master/appveyor.yml
I tried multiple things, but I can not make it work. Do you have any hint of what is going on?

Best regards,

**Comment by rossbar** [comment]
Installing Graphviz+pygraphviz on Windows has historically been difficult. Pygraphviz-1.7 was recently released and should make it significantly easier to build+install on Windows.

Regarding CI, a recipe was recently added to Graphviz+pygraphviz building+testing via GitHub actions - maybe the [CI config files](https://github.com/pygraphviz/pygraphviz/blob/57d7660d70d085cc206d3d8f6833ed7659101e20/.github/workflows/test.yml#L161-L209) will be helpful.

The specific error in the OP should be resolved in pygraphviz-1.7 so I will close this, but if you're still having trouble getting Graphviz+pygraphviz running on a CI system please open a new issue with the latest info.
