### ISSUE TITLE
can't install pygraphviz python3.6 Anaconda3 win10

### ISSUE THREAD

**Issue by e8180kimo** [pygraphviz/pygraphviz#154]
I run `run python -m pip install git+https://github.com/pygraphviz/pygraphviz.git --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"`

Then It returns:

Failed building wheel for pygraphviz
Running setup.py clean for pygraphviz
Failed to build pygraphviz
Installing collected packages: pygraphviz
Running setup.py install for pygraphviz ... error
Complete output from command C:\Users\xxxx\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-req-build-kh81ij8k\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\xxxx\AppData\Local\Temp\pip-record-82zdsb0t\install-record.txt --single-version-externally-managed --compile --include-path=/usr/include/graphviz --library-path=/usr/lib/graphviz/:
C:\Users\xxxx\Anaconda3\lib\site-packages\setuptools\dist.py:355: UserWarning: Normalizing '1.5.dev' to '1.5.dev0'
  normalized_version,
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\pygraphviz
copying pygraphviz\agraph.py -> build\lib.win-amd64-3.6\pygraphviz
copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.6\pygraphviz
copying pygraphviz\release.py -> build\lib.win-amd64-3.6\pygraphviz
copying pygraphviz\version.py -> build\lib.win-amd64-3.6\pygraphviz
copying pygraphviz\__init__.py -> build\lib.win-amd64-3.6\pygraphviz
creating build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_setup.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.6\pygraphviz\tests
copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.6\pygraphviz\tests
running egg_info
writing pygraphviz.egg-info\PKG-INFO
writing dependency_links to pygraphviz.egg-info\dependency_links.txt
writing top-level names to pygraphviz.egg-info\top_level.txt
reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc\build'
writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.6\pygraphviz
copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.6\pygraphviz
running build_ext
building 'pygraphviz._graphviz' extension
creating build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release
creating build\temp.win-amd64-3.6\Release\pygraphviz
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/graphviz -IC:\Users\xxxx\Anaconda3\include -IC:\Users\e8180\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-amd64-3.6\Release\pygraphviz/graphviz_wrap.obj
graphviz_wrap.c
pygraphviz/graphviz_wrap.c(2987): fatal error C1083: Cannot open include file: 'graphviz/cgraph.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

----------------------------------------
Command "C:\Users\xxxx\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-req-build-kh81ij8k\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\xxxx\AppData\Local\Temp\pip-record-82zdsb0t\install-record.txt --single-version-externally-managed --compile --include-path=/usr/include/graphviz --library-path=/usr/lib/graphviz/" failed with error code 1 in C:\Users\xxxx\AppData\Local\Temp\pip-req-build-kh81ij8k\

**Comment by kevinanewman** [comment]
It looks like your include paths may not be correct.

On Windows you need to tell the installer where your GraphVis is.

For example:
python setup.py install --include-path="C:\Program Files (x86)\Graphviz2.38\include" --library-path="C:\Program Files (x86)\Graphviz2.38\lib\release\lib"

Also your python and GraphVis have to both be 32-bit and 64-bit and you may need to modify a couple pygraphvis files and set up your system PATH. See #197 (comment) for what worked for me.

**Comment by rossbar** [comment]
If Graphviz was installed via the package manager in Linux or homebrew on macOS, it should no longer be necessary to explicitly specify the include and library paths when installing pygraphviz via pip as of version 1.7. See the [updated installation instructions](https://pygraphviz.github.io/documentation/stable/install.html#install) for recommended installation procedures on most common platforms. 

If you are still having problems with header resolution or the docs don't cover your use-case well, please open a new issue with info about your platform and how Graphviz was installed.
