### ISSUE TITLE
Unable to run IPSEP mode.

### ISSUE THREAD

**Issue by adbharadwaj** [pygraphviz/pygraphviz#157]
I am unable to run mode="ipsep". The code runs fine with mode="hier"

/venv/lib/python3.4/site-packages/pygraphviz/agraph.py:1334: RuntimeWarning: Warning: Illegal value ipsep for attribute "mode" in graph () - ignored

Here are the graph attributes:
```
graph [layout=neato,
	levelsgap=0.1,
	mode=ipsep
	];
```

**Comment by dschult** [comment]
See #149   would something like that work?
