### ISSUE TITLE
compiling in "sublime text"-editor

### ISSUE THREAD

**Issue by kleinias** [pygraphviz/pygraphviz#165]
If I run the code beneath with python3 from the terminal, that works wonderfully. 
If I use the compile that with the sublime text editor, I get the following error:
`ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')
`
This problem came up particularly with pygraphviz and no other python modules. 

I will also ask this on the sublime editor forum, for getting to know, what's special with that running routine. (https://forum.sublimetext.com/t/issue-compiling-in-sublime-text-editor/38277)

```
#!/usr/bin/env python
"""
An example showing how to use the interface to the pygraphviz
AGraph class to convert to and from graphviz.

Also see the pygraphviz documentation and examples at
http://pygraphviz.github.io/


"""
# Author: Aric Hagberg (hagberg@lanl.gov)

#    Copyright (C) 2006-2016 by
#    Aric Hagberg <hagberg@lanl.gov>
#    Dan Schult <dschult@colgate.edu>
#    Pieter Swart <swart@lanl.gov>
#    All rights reserved.
#    BSD license.

import networkx as nx

# plain graph

G = nx.complete_graph(5)   # start with K5 in networkx
A = nx.nx_agraph.to_agraph(G)        # convert to a graphviz graph
X1 = nx.nx_agraph.from_agraph(A)     # convert back to networkx (but as Graph)
X2 = nx.Graph(A)          # fancy way to do conversion
G1 = nx.Graph(X1)          # now make it a Graph

A.write('k5.dot')     # write to dot file
X3 = nx.nx_agraph.read_dot('k5.dot') # read from dotfile
```

**Comment by dschult** [comment]
Each version of python you have installed has its own folder of
site-packages that have been installed. It looks like your sublime text
editor is using a different installation of python than what you get from
the command line. You need to either set settings in sublime text to use
the already installed version, or install pygraphviz on the python
installation used by sublime text. This will be true for any packages
unless they are already installed for both python installations.

**Comment by kleinias** [comment]
Oh, that worked, when I specified that version :)
