### ISSUE TITLE
AttributeError: module '_graphviz' has no attribute 'AGRAPH_swigconstant'

### ISSUE THREAD

**Issue by chenweiqian** [pygraphviz/pygraphviz#172]
I have installed pygraphviz successfully. But when I test, it has a problem. And i can‘t search for similar questions. The details of error is below. someone who can help me，thanks!!!

F:\>python testPygraphviz.py
Traceback (most recent call last):
  File "testPygraphviz.py", line 1, in <module>
    import pygraphviz as pgv
  File "C:\Python35\lib\site-packages\pygraphviz\__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "C:\Python35\lib\site-packages\pygraphviz\agraph.py", line 22, in <module>
    from . import graphviz as gv
  File "C:\Python35\lib\site-packages\pygraphviz\graphviz.py", line 317, in <module>
    _graphviz.AGRAPH_swigconstant(_graphviz)
AttributeError: module '_graphviz' has no attribute 'AGRAPH_swigconstant'

**Comment by FailedShack** [comment]
I'm also running into this issue, as if the installation wasn't hard enough.

**Comment by FailedShack** [comment]
I'm also running into this. First installation issues and now this..
Anyone knows what's wrong? Any help would be appreciated.

**Comment by LincolnL** [comment]
I have the same problem.

**Comment by chenweiqian** [comment]
I forget this issue. Sorry.

**Comment by LincolnL** [comment]
What did you do to resolve this issue? I still have it.

**Comment by dorian821** [comment]
Running:

Windows 10
Python 3.6
GraphViz_64
Pygraphviz 1.3

I'm also receiving this error. Does anybody have insight into fixing it?

**Comment by FailedShack** [comment]
This shouldn't have been closed. I too still have the issue.
