### ISSUE TITLE
Strange issue when overwriting keys in node_attr or edge_attr

### ISSUE THREAD

**Issue by jlumpe** [pygraphviz/pygraphviz#173]
I'm observing some strange behavior whenever I set the value of an existing attribute in `AGraph.edge_attr`. Here is a quick example:

```python3
from pygraphviz import AGraph

ag = AGraph()
ag.add_edges_from([
    ('A', 'B'),
    ('B', 'C'),
    ('C', 'A'),
])

ag.edge_attr['len'] = 1
print(ag)

ag.edge_attr['len'] = 2
print(ag)
```

Output:
```
strict graph "" {
	edge [len=1];
	A -- B;
	B -- C;
	C -- A;
}

strict graph "" {
	edge [len=2];
	A -- B	 [len=1];
	B -- C	 [len=1];
	C -- A	 [len=1];
}
```

As you can see, the overwritten value is somehow assigned to the individual nodes themselves. The same thing happens with ``node_attr``:

```python3
from pygraphviz import AGraph

ag = AGraph()
ag.add_edges_from([
    ('A', 'B'),
    ('B', 'C'),
    ('C', 'A'),
])

ag.node_attr['shape'] = 'box'
print(ag)

ag.node_attr['shape'] = 'circle'
print(ag)
```
```
strict graph "" {
	node [shape=box];
	A -- B;
	B -- C;
	C -- A;
}

strict graph "" {
	node [shape=circle];
	A	 [shape=box];
	B	 [shape=box];
	A -- B;
	C	 [shape=box];
	B -- C;
	C -- A;
}
```

This is with pygraphviz 1.5 and Python 3.6.

**Comment by dschult** [comment]
This is a "feature" of the Graphviz cgraph library.  When a default edge attribute is assigned, it only applied to edges created after that assignment. Internally, all the existing edges are explicitly set to the prior edge attribute default when the new attribute default value is set.  Changing that behavior will require changes in Graphviz.

**Comment by rossbar** [comment]
Thanks for the explanation @dschult . I'm +1 for consistency with graphviz, so I will close this. The best way to address this moving forward is probably to start (or contribute to existing) upstream discussion(s).
