### ISSUE TITLE
Unresolved Externals errors on Windows 10 Install

### ISSUE THREAD

**Issue by dbabbitt** [pygraphviz/pygraphviz#179]
http://graphviz.org/Download_windows.php  

Then I could solve riddles, one after the other ...  
Using your command as inspiration, transposed to windows: 

```
pip install --global-option=build_ext --global-option="-IC:\PROGRA~2\Graphviz2.38\include"  --global-option="-LC:\PROGRA~2\Graphviz2.38\lib\release\lib" pygraphviz
```

but now I get "49 unresolved externals"

```
    C:\Users\Andreas\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\PROGRA~2\Graphviz2.38\lib\release\lib /LIBPATH:c:\anaconda\libs /LIBPATH:c:\anaconda\PCbuild\amd64 /LIBPATH:c:\anaconda\PC\VS9.0\amd64 cgraph.lib cdt.lib /EXPORT:init_graphviz build\temp.win-amd64-2.7\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib.win-amd64-2.7\pygraphviz\_graphviz.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\pygraphviz\_graphviz.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\pygraphviz\_graphviz.pyd.manifest
graphviz_wrap.obj : warning LNK4197: export 'init_graphviz' specified multiple times; using first specification
   Creating library build\temp.win-amd64-2.7\Release\pygraphviz\_graphviz.lib and object build\temp.win-amd64-2.7\Release\pygraphviz\_graphviz.exp
graphviz_wrap.obj : error LNK2019: unresolved external symbol agsafeset referenced in function agsafeset_label
graphviz_wrap.obj : error LNK2019: unresolved external symbol agstrdup_html referenced in function agsafeset_label
...
graphviz_wrap.obj : error LNK2019: unresolved external symbol Agundirected referenced in function Swig_var_Agundirected_get
graphviz_wrap.obj : error LNK2019: unresolved external symbol Agstrictundirected referenced in function Swig_var_Agstrictundirected_get
build\lib.win-amd64-2.7\pygraphviz\_graphviz.pyd : fatal error LNK1120: 49 unresolved externals
error: command 'C:\\Users\\Andreas\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120
```

_Originally posted by @drandreaskrueger in https://github.com/pygraphviz/pygraphviz/issues/11#issuecomment-172573720_

**Comment by kevinanewman** [comment]
On windows you need to tell the installer where your GraphVis is.  

For example:
`python setup.py install --include-path=C:\Program Files (x86)\Graphviz2.38\include --library-path=C:\Program Files (x86)\Graphviz2.38\lib\release\lib`

Also your python and GraphVis have to both be 32-bit and 64-bit and you may need to modify a couple pygraphvis files and set up your system PATH. See https://github.com/pygraphviz/pygraphviz/issues/197#issuecomment-509779825 for what worked for me.

**Comment by rossbar** [comment]
The pygraphviz-1.7 release includes fixes for building on Windows. Please see the [updated installation docs](https://pygraphviz.github.io/documentation/stable/install.html#windows) for recommendations re: installing Graphviz and pygraphviz on Windows. If issues persist or your use-case is not covered by the docs, please open a new issue with the latest info.

**Comment by dbabbitt** [comment]
Here is some python code that later readers can use to sort out their environment variables (via the Advanced System Settings in their control panel) to ensure that pygraphviz picks the correct one:


```
# Get paths of graphviz programs
import pygraphviz as pgv

A = pgv.AGraph()
progs_list = ['neato', 'dot', 'twopi', 'circo', 'fdp', 'nop', 'wc', 'acyclic', 'gvpr', 'gvcolor',
              'ccomps', 'sccmap', 'tred', 'sfdp', 'unflatten']
for prog in progs_list:
    try:
        runprog = A._get_prog(prog)
        print(f'{runprog}')
    except ValueError as e:
        print(f'{prog} gets this error: {str(e).strip()}')
```
