### ISSUE TITLE
FR: add support for IPython / Jupyter rich display

### ISSUE THREAD

**Issue by mjpieters** [pygraphviz/pygraphviz#182]
Can support for a SVG [IPython Rich Display hook](https://ipython.readthedocs.io/en/stable/config/integrating.html#integrating-rich-display) be added to the `AGraph` class?

That would make it trivial to use `AGraph()` instances in a Jupyter notebook to automatically display the resulting graph by simply echoing the `AGraph` instance. The implementation can be as simple as:

```python
def _render_svg_(self):
    return self.draw(format='svg').decode(self.encoding)
```

This would compliment the way PIL and matplotlib figures are handled. The `graphviz` Python project [also implements this hook](https://graphviz.readthedocs.io/en/stable/manual.html#jupyter-notebooks) (see [their just-as-minimal implementation](https://github.com/xflr6/graphviz/blob/72d3f46321845923cfaf47222bde3e4e18157626/graphviz/files.py#L105-L106).

**Comment by ankostis** [comment]
I think it is `_repr_svg_().

**Comment by dabreese00** [comment]
Yes, the code provided by @mjpieters with the modification mentioned by @ankostis works perfectly for me.

You can even just add this method to the `AGraph` class dynamically at runtime.  Put this code in your notebook:

```python
def _repr_svg_(self):
    return self.draw(format='svg').decode(self.encoding)

setattr(pgv.AGraph, '_repr_svg_', _repr_svg_)
```

Now if I do e.g.

```python
d = {"1": {"2": None}, "2": {"1": None, "3": None}, "3": {"2": None}}

A = pgv.AGraph(d)
A.layout()
A
```
the Jupyter notebook displays the SVG automatically.

Should one of us just make a PR for this?  It seems like the "feature" is just 2 lines of code in a single class, could hardly be simpler.  And a pretty big usability benefit for anyone using Jupyter notebooks (probably a lot of people these days).

@jarrodmillman  I haven't contributed to this project before, but I'd be happy to try to make a PR if it would help.

**Comment by rossbar** [comment]
A PR for this feature would be welcome!

**Comment by MridulS** [comment]
Fixed in https://github.com/pygraphviz/pygraphviz/pull/367
