### ISSUE TITLE
Creating a Windows Conda-forge  package (help needed)

### ISSUE THREAD

**Issue by melund** [pygraphviz/pygraphviz#185]
I am trying to create a windows conda-forge package for the pygraphviz. And need assistance from people who have build pygraphviz for windows before (@diogolr, @RobinZerafa or anyone else). 

Conda-forge feedstock PR:  https://github.com/conda-forge/pygraphviz-feedstock/pull/3

The first obstacle was that the win graphviz conda-forge package did not contain any lib/include files. But that is fixed now, and it got me a little further.

I have tried things suggested on different github issues (for example https://github.com/pygraphviz/pygraphviz/issues/74#issuecomment-413885258) but with no luck. 

I am stuck with [this linker error](https://ci.appveyor.com/project/conda-forge/pygraphviz-feedstock/builds/21766432/job/2t1m1uncvislvjt2#L703): 
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:%PREFIX%\Library\lib/graphviz /LIBPATH:%PREFIX%\libs /LIBPATH:%PREFIX%\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64" /LIBPATH:%PREFIX%\Library\lib cdt.lib cgraph.lib /EXPORT:PyInit__graphviz build\temp.win-amd64-3.6\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib.win-amd64-3.6\pygraphviz\_graphviz.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\pygraphviz\_graphviz.cp36-win_amd64.lib
graphviz_wrap.obj : warning LNK4197: export 'PyInit__graphviz' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.6\Release\pygraphviz\_graphviz.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\pygraphviz\_graphviz.cp36-win_amd64.exp
graphviz_wrap.obj : error LNK2001: unresolved external symbol agwrite
graphviz_wrap.obj : error LNK2001: unresolved external symbol agisdirected
...
```

**Comment by melund** [comment]
Probably also related to this: https://github.com/pygraphviz/pygraphviz/issues/131

**Comment by nehaljwani** [comment]
The main problem is: https://github.com/pygraphviz/pygraphviz/issues/58#issuecomment-197744738

**Comment by nehaljwani** [comment]
Reported the issue here: https://github.com/conda-forge/graphviz-feedstock/issues/33

**Comment by jamesmyatt** [comment]
I think I agree that the issue is the compiled graphviz lib files. It's clear that the right information is being passed to link.exe, but it's unable to use the .lib files referenced.
