### ISSUE TITLE
DLL load failed when importing pygraphviz

### ISSUE THREAD

**Issue by zjx1805** [pygraphviz/pygraphviz#186]
I am using Anaconda 3 with VSCode and with python 3.65 on Windows10 64 bit. I installed the pygraphviz using the instructions given at [here](https://github.com/pygraphviz/pygraphviz/issues/74#issuecomment-413885258). However, when I tried to run the script in VSCode with only one line: `import pygraphviz`, it gives the following error:

`Traceback (most recent call last):
  File "e:\aa.py", line 3, in <module>
    import pygraphviz
  File "C:\Users\markz\AppData\Roaming\Python\Python36\site-packages\pygraphviz\__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "C:\Users\markz\AppData\Roaming\Python\Python36\site-packages\pygraphviz\agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "C:\Users\markz\AppData\Roaming\Python\Python36\site-packages\pygraphviz\graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "C:\Users\markz\AppData\Roaming\Python\Python36\site-packages\pygraphviz\graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.`

From [this](https://github.com/pygraphviz/pygraphviz/issues/165#issue-348190683) issue, I thought I installed the package under the wrong folder. However, when I run the code in the terminal in VSCode, it gives the same error. The code that VSCode actually executed in the terminal are
`C:\ProgramData\Anaconda3\Scripts\activate base`
`C:/ProgramData/Anaconda3/python.exe e:/aa.py`

However, when I copied these two lines of code to the cmd in the Windows, it runs without error. So I am now confused as of why the same code gives different result when running in the terminal from VSCode and from Windows itself? Did I install the pygraphviz into the wrong folder? Any help would be greatly appreciated!

**Comment by 8jclxbl** [comment]
Hey, I got the same error under the VsCode. But when I copied codes to the cmd of the Windows, I got another: `ImportError: DLL load failed:%1 is not a valid Win32 application`.

**Comment by mplunney** [comment]
I'm getting the same error (though can't say whether or not it's the exact same trouble that @8jclxbl is experiencing). Thought the verbose exception traceback in Jupyter might have some insight.

Win 10, Python 3.7.3, Conda 4.6.11. Everything's 64-bit (or at least intended to be). Installed with @alubbock's [installer](https://anaconda.org/alubbock/pygraphviz): `conda install -c alubbock pygraphviz`, seemingly with no problems.

```
%xmode Verbose
import pygraphviz as pgv

Exception reporting mode: Verbose
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-427a4693989a> in <module>
      1 get_ipython().run_line_magic('xmode', 'Verbose')
----> 2 import pygraphviz as pgv
        global pygraphviz = undefined
        global pgv = undefined

C:\ProgramData\Anaconda3\lib\site-packages\pygraphviz\__init__.py in <module>
     56 __license__  = release.license
     57 
---> 58 from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
        global agraph = undefined
        global AGraph = undefined
        global Node = undefined
        global Edge = undefined
        global Attribute = undefined
        global ItemAttribute = undefined
        global DotError = undefined
     59 
     60 __all__=[

C:\ProgramData\Anaconda3\lib\site-packages\pygraphviz\agraph.py in <module>
     20 from collections import MutableMapping
     21 
---> 22 from . import graphviz as gv
        global graphviz = undefined
        global gv = undefined
     23 
     24 _DEFAULT_ENCODING = 'UTF-8'

C:\ProgramData\Anaconda3\lib\site-packages\pygraphviz\graphviz.py in <module>
     26                 fp.close()
     27             return _mod
---> 28     _graphviz = swig_import_helper()
        global _graphviz = undefined
        global swig_import_helper = <function swig_import_helper at 0x00000287F0BBF1E0>
     29     del swig_import_helper
     30 else:

C:\ProgramData\Anaconda3\lib\site-packages\pygraphviz\graphviz.py in swig_import_helper()
     22         if fp is not None:
     23             try:
---> 24                 _mod = imp.load_module('_graphviz', fp, pathname, description)
        _mod = undefined
        imp.load_module = <function load_module at 0x00000287F0832510>
        fp = <_io.BufferedReader name='C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pygraphviz\\_graphviz.cp37-win_amd64.pyd'>
        pathname = 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pygraphviz\\_graphviz.cp37-win_amd64.pyd'
        description = ('.cp37-win_amd64.pyd', 'rb', 3)
     25             finally:
     26                 fp.close()

C:\ProgramData\Anaconda3\lib\imp.py in load_module(name='_graphviz', file=<_io.BufferedReader name='C:\\ProgramData\\Anaco...kages\\pygraphviz\\_graphviz.cp37-win_amd64.pyd'>, filename=r'C:\ProgramData\Anaconda3\lib\site-packages\pygraphviz\_graphviz.cp37-win_amd64.pyd', details=('.cp37-win_amd64.pyd', 'rb', 3))
    240                 return load_dynamic(name, filename, opened_file)
    241         else:
--> 242             return load_dynamic(name, filename, file)
        global load_dynamic = <function load_dynamic at 0x00000287F0832730>
        name = '_graphviz'
        filename = 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pygraphviz\\_graphviz.cp37-win_amd64.pyd'
        file = <_io.BufferedReader name='C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pygraphviz\\_graphviz.cp37-win_amd64.pyd'>
    243     elif type_ == PKG_DIRECTORY:
    244         return load_package(name, filename)

C:\ProgramData\Anaconda3\lib\imp.py in load_dynamic(name='_graphviz', path=r'C:\ProgramData\Anaconda3\lib\site-packages\pygraphviz\_graphviz.cp37-win_amd64.pyd', file=<_io.BufferedReader name='C:\\ProgramData\\Anaco...kages\\pygraphviz\\_graphviz.cp37-win_amd64.pyd'>)
    340         spec = importlib.machinery.ModuleSpec(
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
        global _load = <function _load at 0x00000287ED729C80>
        spec = ModuleSpec(name='_graphviz', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x00000287F0BC5E10>, origin='C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pygraphviz\\_graphviz.cp37-win_amd64.pyd')
    343 
    344 else:

ImportError: DLL load failed: The specified module could not be found.
```

Any help would be greatly appreciated!

**Comment by auphofBSF** [comment]
@alubbock's installer as described https://github.com/pygraphviz/pygraphviz/issues/186#issuecomment-481760487  by @mplunney works Great, thanks both

`conda install graphviz pygraphviz -c alubbock` 

My conda env. Python 3.6.8 |Anaconda 4.2.0 (64-bit)|  [MSC v.1916 64 bit (AMD64)] on win32 Windows/10.0.17134

**Comment by juancaros** [comment]
I have a similar issue. Anaconda 3 and Python 3.7.3 on Win10 64-bit (conda 4.6.14). When I use @alubbock's installer I get the following message: 

```
C:\ProgramData\Anaconda3\lib\site-packages\pygraphviz\agraph.py in _get_prog(self, prog)
   1321             runprog = self._which(prog)
   1322         except:
-> 1323             raise ValueError("Program %s not found in path." % prog)
   1324 
   1325         return runprog

ValueError: Program sfdp not found in path.
```

I noticed that alubbock's graphviz is version 2.41 and the version I installed from their website is 2.38. When I install this version (2.41), some of graphviz programs are on root (e.g. dot) but not the one I require (sfdp). My guess is that by installing a newer version I have PATH issues. Any ideas?

**Comment by NdaAzr** [comment]
Thank you @mplunney. It works for me.

**Comment by ramoncerna** [comment]
@mplunney Thanks a lot!!!! tha solutions is: 
conda install graphviz pygraphviz -c alubbock

**Comment by rossbar** [comment]
Pygraphviz 1.7 was just released and fixes some of the things that made building on Windows difficult. Please see the [updated install instructions](https://pygraphviz.github.io/documentation/stable/install.html#windows) for details on the recommended build/install procedure for pygraphviz on Windows. Note that the recommended installation is based on a 64-bit version of Graphviz - if for some reason you have to use 32-bit Windows or otherwise run into issues with the Windows install, please open a new issue.

**Comment by FTamas77** [comment]
I've the same issue. I don't use conda, but pip. The upper solution does not work for me.
I could install pygraphviz, but later I have this:


[WinError 2] "dot" not found in path.
ImportError: DLL load failed while importing _graphviz: The specified module could not be found.

During handling of the above exception, another exception occurred:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Any idea?

**Comment by hhoppe** [comment]
@FTamas77 

I was able to get it to run by including the `Graphviz/bin` directory (which contains all the *.exe and *.dll) into the PATH *before* any `import pygraphviz`.

```
    if sys.platform == 'win32':
      path = pathlib.Path(r'C:\Program Files\Graphviz\bin')
      if path.is_dir() and str(path) not in os.environ['PATH']:
        os.environ['PATH'] += f';{path}'
```

The importance of the `PATH` variable should be mentioned in the install instructions.
