### ISSUE TITLE
New release for fixed deprecation warning for collections import

### ISSUE THREAD

**Issue by 0xB767B** [pygraphviz/pygraphviz#193]
For my project (with pygraphviz installed via pip) continuous integration fails with:

```DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working```

I've found that this has already been fixed #190.

Would it be possible to make a new release with that fix included?

Many thanks and regards!

**Comment by unigiriunini** [comment]
My project also fails due to this warning.
When is the next release?

**Comment by dschult** [comment]
This is indeed in the latest source and will be released for v1.6 soon.

**Comment by jarrodmillman** [comment]
This should be fixed in v1.6:  https://pypi.org/project/pygraphviz/1.6/
