### ISSUE TITLE
Set layout of an AGraph

### ISSUE THREAD

**Issue by calincru** [pygraphviz/pygraphviz#198]
Correct me if I'm wrong, but it seems that it's not possible to specify/set the layout of a graph. This is needed, for instance, when one wants to draw two graphs that differ only in a few edges.

**Comment by tan-wei** [comment]
I don't think graphviz can do what you want.

**Comment by dschult** [comment]
Yes -- Graphviz can do just about anything... 
See [the FAQ](https://graphviz.gitlab.io/faq/#FaqDotWithNodeCoords)
