### ISSUE TITLE
Osage layout not supported

### ISSUE THREAD

**Issue by ktavabi** [pygraphviz/pygraphviz#205]
`graphviz_layout(G, prog='osage')` fails with 

> ValueError: Program osage is not one of: neato, dot, twopi, circo,...

**Comment by OmenApps** [comment]
Same with `patchwork`

Here's the graphviz docs with the latest layout engines. Not sure why pygraphviz restricts these when they change from time to time in graphviz.

**Comment by rossbar** [comment]
> Not sure why pygraphviz restricts these when they change from time to time in graphviz.

In the past, there was no library interface to Graphviz --- so pygraphviz had to use the CLI for graphviz programs under-the-hood. The internal list of "supported" progs helps prevent a user accidentally running a non-graphviz command via CLI. Of course, one major downside is that this internal listing of supported programs can get out-of-sync with Graphviz itself. 

There is an *experimental* attempt at interfacing with Graphviz via library calls that is exposed for layouts with the private `_layout` method, e.g.

```python
>>> import pygraphviz as pgv
>>> A = pgv.AGraph()
>>> A.add_path([1, 2, 3, 4])
>>> A._layout(prog="patchwork")
```
Whether or not this will work for you will depend on the level of support for library calls in the specific version of Graphviz on your system.

**Comment by rossbar** [comment]
#393 should address this for now - the appropriate long-term solution is to switch to the Graphviz library interface so that this internal listing of "supported" commands no longer needs to be maintained.
