### ISSUE TITLE
ImportError: libcdt.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by enerai** [pygraphviz/pygraphviz#215]
I try to install pygraphviz with DGL in centos. I have already set the 
```
           include_dirs=["/usr/local/include/graphviz/"],
           library_dirs=["/usr/local/lib/"]
```
in setup.py and use `python setup.py install` to install pygraphviz.

I have checked there are `cgraph.h` and `libcdt.so.5` in the above dirs.

However, when I `import pygraphviz as pgv`, the following error appears:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-474595e3b329> in <module>
----> 1 import pygraphviz as pgv

~/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pygraphviz/__init__.py in <module>
     56 __license__  = release.license
     57 
---> 58 from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
     59 
     60 __all__=[

~/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pygraphviz/agraph.py in <module>
     25     from collections import MutableMapping
     26 
---> 27 from . import graphviz as gv
     28 
     29 _DEFAULT_ENCODING = 'UTF-8'

~/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pygraphviz/graphviz.py in <module>
     26                 fp.close()
     27             return _mod
---> 28     _graphviz = swig_import_helper()
     29     del swig_import_helper
     30 else:

~/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pygraphviz/graphviz.py in swig_import_helper()
     22         if fp is not None:
     23             try:
---> 24                 _mod = imp.load_module('_graphviz', fp, pathname, description)
     25             finally:
     26                 fp.close()

~/.pyenv/versions/3.7.7/lib/python3.7/imp.py in load_module(name, file, filename, details)
    240                 return load_dynamic(name, filename, opened_file)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:
    244         return load_package(name, filename)

~/.pyenv/versions/3.7.7/lib/python3.7/imp.py in load_dynamic(name, path, file)
    340         spec = importlib.machinery.ModuleSpec(
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 
    344 else:

ImportError: libcdt.so.5: cannot open shared object file: No such file or directory
```

By the way, in the install log, I found that 
`gcc -pthread -shared -L/root/.pyenv/versions/3.7.7/lib -L/root/.pyenv/versions/3.7.7/lib build/temp.linux-x86_64-3.7/pygraphviz/graphviz_wrap.o -L/usr/local/lib/ -L/usr/local/lib -lcdt -lcgraph -o build/lib.linux-x86_64-3.7/pygraphviz/_graphviz.cpython-37m-x86_64-linux-gnu.so`
Therefore, I think I have already set the correct settings, but there are still some problems... Would it be possible to give some help?

**Comment by enerai** [comment]
In CentOS 7, the module will find the `libcdt.so.5` in `/usr/lib64/`. After copy the `libcdt.so.5.0.0` to `/usr/lib64/` and make a soft link named `libcdt.so.5`, the problem will be solved.

```
cp /usr/local/lib/libcdt.so.5.0.0 /usr/lib64/
ln -s libcdt.so.5.0.0 libcdt.so.5
```
Note: check whether the files exist before running the instructions

**Comment by rossbar** [comment]
I am going to close this as it seems resolved - thanks for taking the time to share your solution @enerai !

Just FYI the [installation docs](https://pygraphviz.github.io/documentation/stable/install.html#fedora-and-red-hat) were recently updated with instructions for how to build pygraphviz w/ Graphviz installed via standard package managers on rpm-based systems.

**Comment by enerai** [comment]
> I am going to close this as it seems resolved - thanks for taking the time to share your solution @enerai !
> 
> Just FYI the [installation docs](https://pygraphviz.github.io/documentation/stable/install.html#fedora-and-red-hat) were recently updated with instructions for how to build pygraphviz w/ Graphviz installed via standard package managers on rpm-based systems.

I am so glad to see that there is an official solution. Thanks for your update.
