### ISSUE TITLE
RuntimeError: generator raised StopIteration when calling nodes() or edges()

### ISSUE THREAD

**Issue by francescoboc** [pygraphviz/pygraphviz#219]
When I call nodes() or edges() on a AGraph class i get the following error:

> In [2050]: graph.nodes()
> ---------------------------------------------------------------------------
> StopIteration                             Traceback (most recent call last)
> ~/miniconda3/lib/python3.7/site-packages/pygraphviz/agraph.py in nodes_iter(self)
>     381             nh = gv.agnxtnode(self.handle, nh)
> --> 382         raise StopIteration
>     383
> 
> StopIteration:
> 
> The above exception was the direct cause of the following exception:
> 
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-2050-362f91b9803f> in <module>
> ----> 1 graph.nodes()
> 
> ~/miniconda3/lib/python3.7/site-packages/pygraphviz/agraph.py in nodes(self)
>     386     def nodes(self):
>     387         """Return a list of all nodes in the graph."""
> --> 388         return list(self.nodes_iter())
>     389
>     390     def number_of_nodes(self):
> 
> RuntimeError: generator raised StopIteration

**Comment by balloch** [comment]
I am experiencing a similar error, in my case trying to invoke the pygraphviz hooks from NetworkX drawing interface. Any help?

**Comment by balloch** [comment]
I may have figured out the answer: the default channel for anaconda and other sources ships Pygraphviz 1.3, which is incompatible with the changes to handling the unexpected end of Iteration in Python 3.7. Pygraphviz 1.6 handles this correctly. To install Pygraphviz 1.6, remove your current pygraphviz installation, and replace it with the correct install, either by way of `pip install pygraphviz` (where pip is from a python>=3.7 installation, gave me environment compatibility errors) or even better, `conda install -c conda-forge pygraphviz` (worked for me)

**Comment by jarrodmillman** [comment]
I created two new issues:
- https://github.com/conda-forge/graphviz-feedstock/issues/55
- https://github.com/conda-forge/pygraphviz-feedstock/issues/13

And am planning to try to follow-up with anaconda once conda-forge updates things:
- https://anaconda.org/anaconda/graphviz
- https://anaconda.org/anaconda/pygraphviz

It would be great if you could comment and / or thumbs up the conda-forge issues I created.  Hopefully, we can get things fixed soon.
