### ISSUE TITLE
dot-file written and read immediately causes ValueError: agread: bad input data

### ISSUE THREAD

**Issue by vanangamudi** [pygraphviz/pygraphviz#229]
```
nx.nx_agraph.write_dot(G, 'archive-002.dot')
g = nx.nx_agraph.read_dot('archive-002.dot')
```
This is a large graph with more than 100k nodes with non-english text.  Nodes are words from Tamil language dictionary and edges are meaning relationships. When I write this to dot file and read it for later use it throws the agread: bad input data. 

No manual changes have been done to the file. 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/pygraphviz/agraph.py in read(self, path)
   1225             try:
-> 1226                 self.handle = gv.agread(fh, None)
   1227             except ValueError:

ValueError: agread: bad input data

During handling of the above exception, another exception occurred:

DotError                                  Traceback (most recent call last)
<ipython-input-15-a283f7c676c4> in <module>
----> 1 g = nx.nx_agraph.read_dot('archive-002.dot')

~/.local/lib/python3.6/site-packages/networkx/drawing/nx_agraph.py in read_dot(path)
    209         raise ImportError('read_dot() requires pygraphviz ',
    210                           'http://pygraphviz.github.io/')
--> 211     A = pygraphviz.AGraph(file=path)
    212     return from_agraph(A)
    213 

~/.local/lib/python3.6/site-packages/pygraphviz/agraph.py in __init__(self, thing, filename, data, string, handle, name, strict, directed, **attr)
    156         elif filename is not None:
    157             # load new graph from file (creates self.handle)
--> 158             self.read(filename)
    159         elif string is not None:
    160             # load new graph from string (creates self.handle)

~/.local/lib/python3.6/site-packages/pygraphviz/agraph.py in read(self, path)
   1226                 self.handle = gv.agread(fh, None)
   1227             except ValueError:
-> 1228                 raise DotError("Invalid Input")
   1229             else:
   1230                 self._update_handle_references()

DotError: Invalid Input
```

**Comment by dschult** [comment]
This doesn't look like a parsing error -- more like a find-the-file error. It is still setting up the "handle" for the file using ```gv.agread```, but maybe I'm missing something. Try it with a small 2-node graph and see if you can pin down what's happening.

**Comment by vanangamudi** [comment]
> This doesn't look like a parsing error -- more like a find-the-file error. It is still setting up the "handle" for the file using `gv.agread`, but maybe I'm missing something. Try it with a small 2-node graph and see if you can pin down what's happening.

It works on smaller graphs. I have manually created nodes and written them out and then read. that works fine. But for large graphs with more than 100k nodes I face this issue. The reported error is not helpful for google search.

**Comment by dschult** [comment]
I've created random graphs with 100k nodes and 5M edges and been able to read and write OK.
The error is occurring in ```agread``` which is part of GraphViz so it could be an upstream bug or limitation. You could try reading the dot file with one of GraphViz's tools to try to narrow down the problem. It's hard for me to know -- as you say, the reported error is too vague to say what is really going on.
