### ISSUE TITLE
DOC:  graphviz and libgraphviz-dev are required

### ISSUE THREAD

**Issue by GrzegorzKrug** [pygraphviz/pygraphviz#247]
I think main page (github pages) should contain information about requirements. I'm that kind of person that reads error logs as last, mostly I follow docs and I felt in same pit twice wasting some time.
I am using ubuntu 18.04.

**Comment by rossbar** [comment]
The [installation docs](https://pygraphviz.github.io/documentation/stable/install.html#install) were recently updated with the pygraphviz 1.7, which should be much more explicit about necessary dependencies and provide simple procedures for how to install these dependencies on most popular platforms.

If the new docs fail to address something, please don't hesitate to re-open this or create a PR.
