### ISSUE TITLE
Change err message when including

### ISSUE THREAD

**Issue by t0asty** [pygraphviz/pygraphviz#252]
So far, the error message proposes to try

pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz"

However, it actually seems to require

pip install pygraphviz --install-option="--include-path=/usr/include" --install-option="--library-path=/usr/lib" (so without the /graphviz)

at least on Mac. Does the former work for other platforms?

**Comment by rossbar** [comment]
The installation instructions have been overhauled for the pygraphviz 1.7 release - there should now be working procedures for macOS users who have installed Graphviz either with [homebrew](https://pygraphviz.github.io/documentation/stable/install.html#homebrew) and [macports](https://pygraphviz.github.io/documentation/stable/install.html#macports).

If you run into problems with the new installation procedures (or you have another method that is not covered), please re-open this or open a new issue.
