### ISSUE TITLE
Paths must be specified for install with GraphViz via MacPorts

### ISSUE THREAD

**Issue by SeaQuench** [pygraphviz/pygraphviz#254]
Given various means by which to install python and software packages in general, it is not surprising that some approaches may be more or less tested (or stable) than others. From my experience today, installing pygraphviz using pip, in a virtual environment created with venv, has trouble finding its GraphViz dependencies, whether GraphViz was installed using Mac Ports or Homebrew. The latter is an issue with Homebrew, which does not create the GraphViz libraries needed by pygraphviz. So with GraphViz 2.40.1 installed using Mac Ports 2.6.2 on MacOS 10.15.6 (Catalina), and explicitly providing pygraphviz with the paths, below, pygraphviz appears to have installed successfully; although i would have preferred the wheels to simply work.

pip install --install-option="--include-path=/opt/local/include/" --install-option="--library-path=/opt/local/lib/" pygraphviz
UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting pygraphviz
  Using cached pygraphviz-1.6.zip (117 kB)
Skipping wheel build for pygraphviz, due to binaries being disabled for it.
Installing collected packages: pygraphviz
    Running setup.py install for pygraphviz ... done
Successfully installed pygraphviz-1.6

**Comment by rossbar** [comment]
@SeaQuench @adarshp if you're still having this problem and have the time, would you mind giving #267 a try? I have a hunch that the setuptools defaults might handle this problem better/be less brittle than the custom tooling in `setup_extras`/`setup_commands`. I'm not a mac user, so I'm not sure about the finer points between the mac package managers. Please LMK if you have a chance to give it a try!

**Comment by adarshp** [comment]
@rossbar This did not work for me - I think my pull request (#257) should fix this problem though.

For reference, here are the errors I got with the `investigate-setup` branch:

```
(pygraphviz) ~/git/pygraphviz (investigate-setup) $ pip install -e .
Obtaining file:///Users/adarsh/git/pygraphviz
Installing collected packages: pygraphviz
  Running setup.py develop for pygraphviz
    ERROR: Command errored out with exit status 1:
     command: /Users/adarsh/.venvs/pygraphviz/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/adarsh/git/pygraphviz/setup.py'"'"'; __file__='"'"'/Users/adarsh/git/pygraphviz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/adarsh/git/pygraphviz/
    Complete output (31 lines):
    running develop
    running egg_info
    creating pygraphviz.egg-info
    writing pygraphviz.egg-info/PKG-INFO
    writing dependency_links to pygraphviz.egg-info/dependency_links.txt
    writing top-level names to pygraphviz.egg-info/top_level.txt
    writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
    reading manifest file 'pygraphviz.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /Users/adarsh/.venvs/pygraphviz/lib/python3.7/site-packages/setuptools/dist.py:454: UserWarning: Normalizing '1.7.dev' to '1.7.dev0'
      warnings.warn(tmpl.format(**locals()))
    warning: no files found matching '*.png' under directory 'doc'
    warning: no files found matching '*.html' under directory 'doc'
    warning: no files found matching '*.txt' under directory 'doc'
    warning: no files found matching '*.css' under directory 'doc'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
    writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build
    creating build/temp.macosx-10.15-x86_64-3.7
    creating build/temp.macosx-10.15-x86_64-3.7/pygraphviz
    /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/adarsh/.venvs/pygraphviz/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c pygraphviz/graphviz_wrap.c -o build/temp.macosx-10.15-x86_64-3.7/pygraphviz/graphviz_wrap.o
    pygraphviz/graphviz_wrap.c:2676:10: fatal error: 'graphviz/cgraph.h' file not found
    #include "graphviz/cgraph.h"
             ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/adarsh/.venvs/pygraphviz/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/adarsh/git/pygraphviz/setup.py'"'"'; __file__='"'"'/Users/adarsh/git/pygraphviz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/adarsh/.venvs/pygraphviz/bin/python -m pip install --upgrade pip' command.
```

**Comment by rossbar** [comment]
Thanks @adarshp - yes there are several PRs open with patches to `setup_extra.py`. My hope was that we could rely on the setuptools defaults for finding include/lib paths as that removes a lot of specialized (and apparently brittle) code from pygraphviz.

Just to confirm: this is for graphviz installed via MacPorts correct? Would you mind sharing which version of graphviz is installed and the macports command used for the installation?

**Comment by adarshp** [comment]
@rossbar invoking `port installed | grep graphviz` gives me the following output, which I take to mean that Graphviz 2.41.20171026.1811_2 is active.

```
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
  graphviz @2.40.1_2+pangocairo+x11
  graphviz-devel @2.41.20171026.1811_1+pangocairo+x11
  graphviz-devel @2.41.20171026.1811_2+pangocairo+x11 (active)
```

I don't remember the command I used to install `graphviz` - it was one of either `sudo port install graphviz-devel` or `sudo port install graphviz`.

**Comment by adarshp** [comment]
And yes, this is for graphviz installed via MacPorts.

**Comment by rossbar** [comment]
Awesome, thanks for the info! I'm going to try to set up some containers to test with.

> I don't remember the command I used to install graphviz - it was one of either sudo port install graphviz-devel or sudo port install graphviz.

You may need both - depending on the how the packages are generated, it's possible that `graphviz-devel` is required for the headers (in the "correct" location) and `graphviz` for the libs. This is the case e.g. on Ubuntu, where both `graphviz` and `graphviz-dev` packages are required.

**Comment by dschult** [comment]
Also, it looks like your graphviz is 2.40 while the graphviz-devel is 2.41

**Comment by adarshp** [comment]
@dschult MacPorts keeps one of the versions 'active' - I suspect that the graphviz-devel port supersedes the graphviz port and is what is used when compiling the swig wrapper. Also,  PACKAGE_VERSION is defined as 2.41.20171026.1811 in `/opt/local/include/graphviz/graphviz_version.h`.

**Comment by rossbar** [comment]
@adarshp there's a release candidate for pygraphviz 1.7 out as of today where the custom setup functionality has been entirely removed and the install directions updated. It would be great if you could take a look at the [updated instructions for macports users](https://pygraphviz.github.io/documentation/latest/install.html#macports) and let us know what you think.

**Comment by adarshp** [comment]
@rossbar The instructions look good, thanks for adding them!

**Comment by rossbar** [comment]
Pygraphviz 1.7 has been released with [updated instructions for installing on macOS w/ Graphviz installed via macports](https://pygraphviz.github.io/documentation/stable/install.html#macports). The macports installation procedure is also now running in CI, so hopefully it is sufficient to resolve the problem generally for macOS users who have installed Graphviz w/ macports. If problems persist or new problems crop up, please either re-open this issue or create a new one with updated info.

**Comment by mathematrucker** [comment]
Knowing next to nothing about these things I find it mystifying that anyone knowledgeable enough to build complex apps could be incapable of creating point-and-click installations of them.  My best guess is that OS's are intentionally designed to prevent anybody with an IQ less than 200 from creating easy installations.
