### ISSUE TITLE
"pip install pygraphviz" won't automatically find libgraphviz

### ISSUE THREAD

**Issue by simonrouse9461** [pygraphviz/pygraphviz#255]
I have libgraphviz-dev installed on Ubuntu-20.04 with "sudo apt install libgraphviz-dev". By default, libgraphviz-dev will be installed under /usr/lib/x86_64-linux-gnu/graphviz. However, "pip install pygraphviz" only search for /usr/lib/graphviz, and thus gives an error unless lib path is manually set. Is it possible to let pygraphviz also search under  /usr/lib/x86_64-linux-gnu/graphviz?

**Comment by mcitoler** [comment]
I run into the same issue and https://github.com/pygraphviz/pygraphviz/issues/251#issuecomment-701606853 did the trick for me. There is also https://github.com/pygraphviz/pygraphviz/pull/250 addressing the issue so I'm guessing that this will be fixed in the next release.

**Comment by rossbar** [comment]
The custom setup extensions in pygraphviz that were causing problems with Ubuntu 20.04 have been removed in pygraphviz 1.7. Installing pygraphviz 1.7 on Ubuntu should now work without the need for any intervention in the setup: see [the install instructions](https://pygraphviz.github.io/documentation/stable/install.html#ubuntu-and-debian) for details.

If problems persist, please re-open this or open a new issue with updated info.
