### ISSUE TITLE
Problem with `tred` and `acyclic` methods

### ISSUE THREAD

**Issue by rossbar** [pygraphviz/pygraphviz#308]
The `tred` and `acyclic` methods of AGraph are not working and give uninformative tracebacks. For example, running the example from the `acyclic` docstring:

```python
>>> import pygraphviz as pgv
>>> A = pgv.AGraph()
>>> B = A.acyclic(copy=True)
Traceback (most recent call last)
<ipython-input-6-2298558dd82c> in <module>
----> 1 A.acyclic(copy=True)

~/repos/pygraphviz/pygraphviz/agraph.py in acyclic(self, args, copy)
   1431         See the graphviz "acyclic" program for details of the algorithm.
   1432         """
-> 1433         data = self._run_prog("acyclic", args)
   1434         if copy:
   1435             return self.__class__(string=data.decode(self.encoding))

~/repos/pygraphviz/pygraphviz/agraph.py in _run_prog(self, prog, args)
   1382 
   1383         if not data:
-> 1384             raise OSError(b"".join(errors).decode(self.encoding))
   1385 
   1386         if len(errors) > 0:

OSError:
```

The traceback implies there's something wrong with the `_run_prog` call of Graphviz's `acyclic` and `tred`. This may be a Graphviz version issue.

Platform: Linux
pygraphviz version: 398d1bd
graphviz version: 2.44.1

**Comment by dschult** [comment]
I think tred and acyclic raise an error when the graph is not directed. 
This should read more like:  
```python
A = pgv.AGraph(directed=True)
B = A.acyclic()
```
And maybe it should include `A.add_edge("a", "b")` too, but that doesn't affect the error.
