### ISSUE TITLE
Cannot install pygraphviz

### ISSUE THREAD

**Issue by AdrianAntico** [pygraphviz/pygraphviz#322]
I know this issue isn't unique. Nonetheless, I have graphviz installed and I can find the cgraph.h file inside the graphviz folder structure at C:\Program Files\Graphviz 2.44.1\include\graphviz. I'm using a windows server. Not sure how to proceed to get pygraphviz installed. I've tried various things from stackoverflow to no avail. Let me know what other information you need to help troubleshoot!

Part of error message:
pygraphviz/graphviz_wrap.c(2676): fatal error C1083: Cannot open include file: 'graphviz/cgraph.h': No such file or directory

Thanks,
Adrian

**Comment by rossbar** [comment]
There will be a release candidate coming out soon with improved instructions/support for building on Windows. In the mean time, if you want to try out the latest on `master`, you might be interested in the [recipe used to build & test on Windows for CI](https://github.com/pygraphviz/pygraphviz/blob/85fe3d146e0a54c966824c28d78f20ead089ff7b/.github/workflows/test.yml#L175-L201).

If you already have Graphviz installed (including the .dlls, headers, and .exes), then the `Install packages` step is probably where you'd want to start. If you do end up giving this a try, any feedback would be welcome!

**Comment by AdrianAntico** [comment]
Hi @rossbar 

I just started running some of the script you pointed me to (in PowerShell) and ran into an error on the requirements.txt line. Everything above that worked fine. Any idea how to proceed from here?

# Error here (cannot find file)
python -m pip install -r requirements/test.txt


$PATH = [Environment]::GetEnvironmentVariable("PATH")
        $graphviz_path = "C:\Program Files\Graphviz\bin"
        [Environment]::SetEnvironmentVariable("PATH", "$graphviz_path;$PATH")
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements/test.txt
        python -m pip install --global-option=build_ext `
          --global-option="-IC:\Program Files\Graphviz\include" `
          --global-option="-LC:\Program Files\Graphviz\lib" `
          .
        python -m pip list

1.

**Comment by rossbar** [comment]
This all assumes that you are running from the root level of the repository, so the preamble to this procedure would be something like:

```
git clone https://github.com/pygraphviz/pygraphviz.git
cd pygraphviz
... <above procedure starts here>
```

**Comment by AdrianAntico** [comment]
Ah, gotcha. I'll give it a shot and provide feedback

**Comment by AdrianAntico** [comment]
@rossbar got it work. Thanks for walking me through that!
