### ISSUE TITLE
Python version badge in readme

### ISSUE THREAD

**Issue by veghp** [pygraphviz/pygraphviz#323]
Thanks for developing this package!
I noticed that the readme badge says Python version 3.6, 3.7 and 3.8, but it won't install on 3.6. Indeed the setup doesn't accept versions below 3.7: https://github.com/pygraphviz/pygraphviz/blob/master/setup.py#L6

**Comment by rossbar** [comment]
The Python version badge corresponds to the current stable release, i.e. v1.6, which supports 3.6, 3.7, and 3.8 (see the pypi badge in the README just before the Python version badges). The setup.py on master corresponds to the development version, so pygraphviz 1.7 (coming soon) will support 3.7, 3.8, 3.9.

I can see how the badges get confusing without this latest/stable context, so I'm not against removing the version badge altogether.

**Comment by veghp** [comment]
Thanks for the explanation!
(I see now that there is a similar issue with the version badge v1.6, while the code version is [1.7rc2.dev0](https://github.com/pygraphviz/pygraphviz/blob/master/pygraphviz/__init__.py#L22))

**Comment by jarrodmillman** [comment]
I removed the confusing badges.
