### ISSUE TITLE
utilize / allow gaphviz attrs in formatting png

### ISSUE THREAD

**Issue by m10d** [pygraphviz/pygraphviz#336]
using `pygraphviz==1.7` via `networkx==2.5` integration.  Host is `ubuntu 20.04` with `graphviz` 2.43.0 installed.

`graphviz` supports numerous `attrs` for controlling formatting in graphical outputs.  since `pygraphviz` appears to be a somewhat direct wrapper around the system `graphviz` libraries - it's possible i'm just missing how to do this.  

specifically, i need to change 
- `fontname` to a fixed-width, and 
- `labeljust` to "left" (@dschult provided a workaround for this usage with inline `"\l"`s)

Example:
```
from networkx import DiGraph, nx_agraph
from networkx.drawing.nx_agraph import write_dot

# graph is created via networkx:
graph = DiGraph()
graph.add_edge("node1", "node2")
graph.nodes["node1"]["label"] = "a label to justify for\nnode1"
# ...

# and converted / output to dot & png via (internally) pygraphviz
write_dot(graph, "/tmp/foo.dot") # appears correctly output
a_graph = nx_agraph.to_agraph(graph)
a_graph.layout(prog="dot")

# attempt to add attrs per defs in 
# https://www.graphviz.org/doc/info/attrs.html#d:labeljust
# I care about labeljust + fontname; tried `nojustify` as well because it applies to all of `GCNE` elements

a_graph.graph_attr.update(labeljust="l")  #  <---------------- no effect on output
a_graph.graph_attr.update(nojustify=True)   #  <------------|
a_graph.graph_attr.update(fontname="Liberation Mono") # <--/


a_graph.draw("/tmp/foo.png") # <-- PNG outputs successfully, 
#                                  but all node text is CENTER justified
```

adding `attr`s has no effect on `png` output

**Comment by dschult** [comment]
Read the docs for `labeljust` that you link to.
It says that this affects the "cluster labels",
Not the node labels.

The node labels are justified by characters in the label itself. Ending a label with "\n" centers it, while "\l" and "\r" make that label left or right justified. You can even mix and match if your labels have multiple lines: "all\lmixed\rup".

**Comment by m10d** [comment]
@dschult  thanks for your reply.  I did RTFM; I'm a total noob to graphviz but I read that 


Name | Used By | Type | Default
-- | -- | -- | --
labeljust | **G**C | string | "c" |   |  

`G` being **graph**-level attr.  The text section of the doc says the same - `Valid for: Clusters, Graphs.`

Am I mis-understanding what `Graph` level means here?

**Comment by m10d** [comment]
another note - thank you for the hint on using using `"\l"` in the label itself; this isn't noted in the `labeljust` but now that I know about it i can find that "minimally" referenced in that page of the - although FWIW if you're involved in the docs it could be called out a bit clearer (or even in the `labeljust` section directly -  w.r.t. least-surprise; `"\r"` and `"\n"` are standard `ascii` escapes while `"\l"` is not (and "\r" is being repurposed in a different way here)

**for any readers** - __replacing__ a `\n` with `"\l"` will left-justify the line.  (on a linux system; might behave different on windows; note that (in python at least) `"\l"`==`r"\l"`==`[0x5c,0x6c]`)

unfortunately this doesn't solve my underlying issue (and as above - I believe I am using the `graph_attr` per the documentation) - I have the same problem with `font` choice - says it applies to `graph` but the following has no effect:
```
    formattable_graph.graph_attr.update(fontname="Liberation Mono")
```
Seems like the same bug or usage issue, so I just posted about my first occurrence.

**Comment by dschult** [comment]
I read the `labeljust` docs to say that it is a graph-wide attribute for the justification of cluster labels.
I'm not an expert in GraphViz. I've worked on pygraphviz but we're mostly focused on the interface from python to GraphViz. The [list of attributes I found in the graphviz docs ](https://graphviz.org/doc/info/attrs.html) doesn't seem to have a graph-wide justification attribute for node labels.

**Comment by m10d** [comment]
Ok, I can see that reading as well @dschult ; I'm fine assuming that you are correct there and it just doesn't apply as i'm using it (and the workaround you provided is good enough)

There is still the other graphviz attribute, `fontname` that seems equally applicable in this issue; as far as I can tell i'm using it appropriately - HOWEVER

I dug around some more, and was able to reproduce this (lack of) formatting using the `.dot` output and native `graphviz` tools `-Tpng`.  It appears that `graph` attrs, at least for `fontname` are not _inherited_, they must be defined per `graph` / `node` / `edge`.

So adding the following fixes the issue.  DuckDuckGo'ing around, it appears that you can probably also define these as *file-wide* (per each of graph/node/edge) defaults, too.

```
    for node in formattable_graph.iternodes():
        node.attr["fontname"] = "Liberation Mono"
```

**Comment by m10d** [comment]
appears this is a "documentation but" in `graphviz`, not a `pygraphviz` issue.
