### ISSUE TITLE
PyGraphviz vs PyDot how does one decide which one to use?

### ISSUE THREAD

**Issue by brando90** [pygraphviz/pygraphviz#346]
I know this might be a hard question to remain unbiased but I thought having this discussion on the web somewhere might be useful for people trying to make a decision on which library to use. But what are the cons & pros or how should one decide to use PyGraphviz vs PyDo to visualize graphs in Python? (my own bias is that I am use the dgl deep learning library)

related resources:
- python.libhunt.com/compare-pydot-vs-pygraphviz
- qr.ae/pGtb7r
- https://stackoverflow.com/questions/37353199/graphviz-vs-pygraphviz

**Comment by rossbar** [comment]
This is (at least partially) addressed in networkx/networkx#5365, so I will point to the discussion there. If there are further questions, please update the discussion topic!
