### ISSUE TITLE
pygraphviz -missing

### ISSUE THREAD

**Issue by noussaibamel** [pygraphviz/pygraphviz#350]
Hi everyone, 
I had installed phython3 but during the installation of the NS3 I found that the pygraphviz was not installed. i tried with pip install and apt-get install the answer is: 
noussaiba@noussaiba-SATELLITE-C855-1EN:~$ sudo apt-get install pygraphviz
[sudo] Mot de passe de noussaiba : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet pygraphviz

 the same with sudo apt-get install python3-pygraphviz

I also try with pip install, here is the answer
noussaiba@noussaiba-SATELLITE-C855-1EN:~$ pip install pygraphviz
Requirement already satisfied: pygraphviz in /usr/lib/python3/dist-packages (1.5)

and When I check with bake.py show, it gives me that the pygraphviz not installed:

noussaiba@noussaiba-SATELLITE-C855-1EN:~$ bake.py show
module: qt (enabled)
  No dependencies!
module: g++ (enabled)
  No dependencies!
module: setuptools (enabled)
  No dependencies!
module: gi-cairo (enabled)
  No dependencies!
module: gir-bindings (enabled)
  No dependencies!
module: pygobject (enabled)
  No dependencies!
module: pygraphviz (enabled)
  No dependencies!
module: python3-dev (enabled)
  No dependencies!
module: python-dev (enabled)
  No dependencies!
module: pybindgen-0.19.0.post4+ng823d8b2 (enabled)
  depends on:
     python-dev (optional:True)
     setuptools (optional:False)
module: pyviz-gtk3-prerequisites (enabled)
  depends on:
     python3-dev (optional:True)
     pygraphviz (optional:True)
     pygobject (optional:True)
     gi-cairo (optional:True)
     gir-bindings (optional:True)
module: netanim-3.108 (enabled)
  depends on:
     qt (optional:False)
     g++ (optional:False)
module ns: ns-3.29 (enabled)
  depends on:
     netanim-3.108 (optional:True)
     pybindgen-0.19.0.post4+ng823d8b2 (optional:True)
     pyviz-gtk3-prerequisites (optional:True)

-- System Dependencies --
 > g++ - OK
 > gi-cairo - OK
 > gir-bindings - OK
 > pygobject - OK
 
**> pygraphviz - Missing
   >> The pygraphviz is not installed, try to install it.
   >> Try: "sudo apt-get install python3-pygraphviz", if you have sudo rights**

 > python-dev - OK
 > python3-dev - OK
 > qt - OK
 > setuptools - OK

what should i do?

**Comment by rossbar** [comment]
This looks to me like a case of mixing up different installation/package management schemes. Generally, a Python environment manager (e.g. `venv`, `conda`, `virtualenv`) is preferred to using a system package manager (e.g. `apt-get`) to install Python dependencies.

Since you are on a debian-based system, installation of pygraphviz should be straightforward as the Graphviz dependencies can be installed with `apt`:

```bash
sudo apt-get install graphviz graphviz-dev
```

Once you have Graphviz installed, you could for example try:

```
python3 -m venv pgv-testenv
source pgv-testenv/bin/activate
pip install pygraphviz
```

**Comment by noussaibamel** [comment]
by reinstalling ubuntu; I redid the installation of python and everything was nichel, thank you very much
