### ISSUE TITLE
Windows DLL Permission Changes for Python 3.8+

### ISSUE THREAD

**Issue by tommychinjr** [pygraphviz/pygraphviz#360]
I recently stumble upon a DLL problem using pygrpahviz on Windows with Python 3.10b4

```
C:\Users\user>python
Python 3.10.0b4 (tags/v3.10.0b4:2ba4b20, Jul 10 2021, 17:36:48) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygraphviz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\pygraphviz\__init__.py", line 24, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "C:\Python310\lib\site-packages\pygraphviz\agraph.py", line 15, in <module>
    from . import graphviz as gv
  File "C:\Python310\lib\site-packages\pygraphviz\graphviz.py", line 13, in <module>
    from . import _graphviz
ImportError: DLL load failed while importing _graphviz: The specified module could not be found.
```

Debugging the problem revealed that Python 3.8 changed the way ctypes are loaded for Windows to specific folders for security purposes

```
DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution. If your application relies on these mechanisms, you should check for add_dll_directory() and if it exists, use it to add your DLLs directory while loading your library. Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer). (Contributed by Steve Dower in bpo-36085.)
```
Link: https://docs.python.org/3/whatsnew/3.8.html

GraphViz has a set of DLL files that are in its respective bin folder (i.e., `C:\Program Files\Graphviz\bin`). The change in Python 3.8 will not allow pygraphviz to run correctly as python will not load the GraphViz's bin folder when one does `import pygraphviz`

The work around to solve the problem:

```
import os
os.add_dll_directory("C:/Program Files/Graphviz/bin")
import pygraphviz as pgv
```

Writing this issue ticket so that others may find this thread to the work around until someone documents the workaround in the best place

Cheers and happy coding everyone!

**Comment by rossbar** [comment]
What version of pygraphviz are you using? Note that this should be fixed in the latest version v1.7: 

https://github.com/pygraphviz/pygraphviz/blob/812e75c98bdd429e3ef5ca0733911b8b21f38a5c/pygraphviz/__init__.py#L11-L19 

which was added in #318. If you are still having issues related to this in v1.7, please let us know.
