### ISSUE TITLE
Mac OS failed building wheel

### ISSUE THREAD

**Issue by Elocien** [pygraphviz/pygraphviz#369]
Similar issue to #163. I have graphviz installed in homebrew and pip, but getting the following error:

"
ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/lucian/Downloads/pygraphviz-1.7/setup.py'"'"'; __file__='"'"'/Users/lucian/Downloads/pygraphviz-1.7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/11/yc5pj98n4mb3dzq1_mxwmtmm0000gn/T/pip-record-9nf_mfcx/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/pygraphviz
         cwd: /Users/lucian/Downloads/pygraphviz-1.7/
    Complete output (51 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-x86_64-3.9
    creating build/lib.macosx-11-x86_64-3.9/pygraphviz
    copying pygraphviz/scraper.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz
    copying pygraphviz/graphviz.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz
    copying pygraphviz/__init__.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz
    copying pygraphviz/agraph.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz
    copying pygraphviz/testing.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz
    creating build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_unicode.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_scraper.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_readwrite.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_string.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/__init__.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_html.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_node_attributes.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_drawing.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_subgraph.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_close.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_edge_attributes.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_clear.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_layout.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_attribute_defaults.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    copying pygraphviz/tests/test_graph.py -> build/lib.macosx-11-x86_64-3.9/pygraphviz/tests
    running egg_info
    writing pygraphviz.egg-info/PKG-INFO
    writing dependency_links to pygraphviz.egg-info/dependency_links.txt
    writing top-level names to pygraphviz.egg-info/top_level.txt
    reading manifest file 'pygraphviz.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.png' under directory 'doc'
    warning: no files found matching '*.txt' under directory 'doc'
    warning: no files found matching '*.css' under directory 'doc'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
    adding license file 'LICENSE'
    writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
    copying pygraphviz/graphviz.i -> build/lib.macosx-11-x86_64-3.9/pygraphviz
    copying pygraphviz/graphviz_wrap.c -> build/lib.macosx-11-x86_64-3.9/pygraphviz
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build/temp.macosx-11-x86_64-3.9
    creating build/temp.macosx-11-x86_64-3.9/pygraphviz
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c pygraphviz/graphviz_wrap.c -o build/temp.macosx-11-x86_64-3.9/pygraphviz/graphviz_wrap.o
    clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/lucian/Downloads/pygraphviz-1.7/setup.py'"'"'; __file__='"'"'/Users/lucian/Downloads/pygraphviz-1.7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/11/yc5pj98n4mb3dzq1_mxwmtmm0000gn/T/pip-record-9nf_mfcx/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/pygraphviz Check the logs for full command output.
"

Where this seems to be the main issue: clang:` error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11

Any tips on how to fix this?

**Comment by rossbar** [comment]
AFAICT this is a mac build env problem and is not specific to pygraphviz, see e.g. https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target.

Since this doesn't seem to be pygraphviz-specific, I'm going to close this; however, if you run into additional problems that seem to be specific to building the pygraphviz wheel, please feel free to reopen.

**Comment by Elocien** [comment]
ok no worries, thanks for the help!
