### ISSUE TITLE
Contributor docs

### ISSUE THREAD

**Issue by dabreese00** [pygraphviz/pygraphviz#378]
As a newbie contributor of a single PR, I had some novice-level struggles getting setup to run the main branch and tests locally.  I took notes for myself for the future.  I'm happy to share these notes if it helps.

Maybe they could be generalized and put into a `CONTRIBUTING.txt` or something.  I looked a few times but didn't find any kind of contributing docs, here or on the website.

I could offer a quick "getting started" outline; something along the lines of (rough draft):

1. Install graphviz with development headers (refer to `INSTALL.txt` for per-OS instructions).
2. Clone the repository and `cd` into it.
3. (Install/switch to an appropriate Python version and) Create and activate a virtualenv.
4. `python -m pip install --upgrade pip wheel setuptools`
5. `python -m pip install -r requirements/developer.txt`
6. `python -m pip install -r requirements/tests.txt`
7. `python setup.py develop`

Run `black` to format your code.

Run tests with: `pytest --durations=10 --pyargs pygraphviz`

Finally cleanup, if your virtualenv directory is inside the git root, delete it before committing.

... would have saved me a pretty big chunk of time, if I'd found it documented somewhere.  While some of it was familiar to me, I ended up having to cobble together other key elements of this process from various scattered references, including `INSTALL.txt`, reading through `graphviz.py` and `setup.py`, [the Github Actions CI hooks](https://github.com/pygraphviz/pygraphviz/blob/85fe3d146e0a54c966824c28d78f20ead089ff7b/.github/workflows/test.yml), and [the `setuptools` user docs](https://setuptools.pypa.io/en/latest/userguide/development_mode.html).  That took a bit of doing for me, although it might have been self-explanatory for someone with more general Python development experience.

Overall, I think something like this could probably help other newbies who want to contribute, too.  And a contributing doc would of course always be a good place for any other guidelines that the maintainers might want to convey to new contributors.

If adding something like this to the repository would be of interest, and if I could help in any way or make a PR, let me know.

**Comment by MridulS** [comment]
@dabreese00 That would be great! Thanks!

If you need some inspiration you can look at https://networkx.org/documentation/stable/developer/contribute.html

**Comment by jarrodmillman** [comment]
@dabreese00 That would be excellent!  The source for the page Mridul pointed to above is here:

- https://github.com/networkx/networkx/blob/main/CONTRIBUTING.rst
- https://github.com/networkx/networkx/blob/main/doc/developer/contribute.rst

We are developing both (although we mainly focus on networkx).  So feel free to just copy the text and modify it as needed.
