### ISSUE TITLE
Import Error: symbol not found in flat namespace '_Agdirected'

### ISSUE THREAD

**Issue by iadubovoy** [pygraphviz/pygraphviz#400]
Hello. First off I am using Anaconda on M1 MacOS. I installed it by specifying where the Graphviz directory was using the homebrew method. When I import pygraphviz in Jupyter this happens:

<img width="1097" alt="96720051-CD7A-46B7-9B26-BEF4689DF33D" src="https://user-images.githubusercontent.com/70456827/158690230-111766c8-0dec-4371-adcd-4e8e8bea53e5.png">

 Any help is much appreciated!

**Comment by MridulS** [comment]
The error message here is similar to https://github.com/pygraphviz/pygraphviz/issues/342 (old GraphViz version seems to have been the problem).

Can you check the version of Graphviz that is being installed here? How are you installing pygraphviz? If you are using conda, make sure to use `conda-forge` channel to get the correct version of `graphviz`.

`conda install --channel conda-forge pygraphviz` (this will also install graphviz for you, so you don't need homebrew to manage that).

**Comment by iadubovoy** [comment]
I was using Graphviz 3.0.0 and installing pygraphviz the same way that the OP of issue #342 installed it. 

I used <i>conda install --channel conda-forge pygraphviz</i> after I created a new environment, and it installed and imported. Thank you so much.
