### ISSUE TITLE
[Question] How stable is `_layout`?

### ISSUE THREAD

**Issue by dantownsend** [pygraphviz/pygraphviz#422]
Hi, I've been using the `_layout` method, which is marked as experimental:

https://github.com/pygraphviz/pygraphviz/blob/8d154321c6ae5c684067d5eadcec8957707f3419/pygraphviz/agraph.py#L1483-L1486

The performance is dramatically better than `layout`, which is important for my application.

Can you provide any guidance on how stable it is? Is it not recommended for production apps? I haven't encountered any issues with it. Thanks!

**Comment by rossbar** [comment]
Great question... I'd say: stable enough that we're trying to switch to it for the next pygraphviz release :) - see #421. Note however that this would result in the removal of the explicit `_layout` method as it would be replacing the builtin `layout` method, so any code that used `_layout` would break.

In practice, there's no way to know for sure as it uses the underlying `libgvc` interface from graphviz, so any kinks in the underlying library will percolate up to pygraphviz. Given [the feedback we've received from graphviz developers](https://github.com/pygraphviz/pygraphviz/issues/167#issuecomment-1085483011) it seems like the right time to try it.

There's no timeline on when the switch will be made though - I intend to work on it over the summer but there are still some tricky things to figure out on the build side.

**Comment by dantownsend** [comment]
@rossbar Thanks a lot for the fast reply - that's really useful.

I'll use `_layout` for now then, and will keep an eye out for future releases where it becomes the default.
