### ISSUE TITLE
[Question] How to add positions to nodes?

### ISSUE THREAD

**Issue by dantownsend** [pygraphviz/pygraphviz#423]
Apologies if this is a dumb question.

I've been able to get everything working, except for setting the `pos` attribute of a node. I'd like to use this with neato.

When I do the following:

```python
graph = pgv.AGraph(directed=False, overlap='voronoi', sep=0.1)

# Add some nodes
graph.add_node(
    1,
    height=1,
    width=1,
    fixedsize="shape",
    shape="box",
    pos=(100.0, 200.0),  # I can't work out the required format for this
)
```

When I run:

```
graph._layout(prog='neato', args='-n')
# OR
graph.layout(prog='neato', args='-n')
```

I get an error like:

```
Error: node 1, position (100.0, 200.0), expected two doubles
```

I've tried floats, decimals, and also a string like `"100,100!"`. I thought floats and doubles were the same thing in Python - do you know where I'm going wrong? Thanks!

**Comment by dschult** [comment]
Try `pos="100.0,200.0"`
But I'm not sure what the full restrictions are. For example, can it have a space after the comma? idk

**Comment by dantownsend** [comment]
@dschult You're right - that works. Many thanks!

The exclamation mark wasn't required, and neither is wrapping it in quotes.
