### ISSUE TITLE
using copy() force converts a "non"-strict graph into a "strict" graph

### ISSUE THREAD

**Issue by spurakan** [pygraphviz/pygraphviz#426]
dot=pgv.AGraph(strict=False, directed=True)    
print("dot:IsStrict:{}".format(dot.is_strict()))
#prints false
temp=dot.copy()
print("temp:IsStrict:{}".format(temp.is_strict()))
#prints true
#copy() carries over the "directed" attribute, but does not carry forward the "strict" attribute of the graph being copied.

**Comment by dschult** [comment]
Thanks for this -- it looks like it also doesn't carry forward the `name` attribute.
This is similar to #354 with fix #356. 
```python
        G = self.__class__(strict=self.strict, directed=self.directed, name=self.name)
```
