### ISSUE TITLE
Build graphviz at install time?

### ISSUE THREAD

**Issue by ganler** [pygraphviz/pygraphviz#437]
Hi, I am curious if there are plans to support bringing the Graphviz binary (or compile from source) when installing pygraphviz. This will benefit a lot the usability of pygrahviz, as currently setting pygraphviz as dependency will break the installation process when the user does not have graphviz installed and it would be better to make it easier to use by bringing a graphviz binary during installation. Thanks! :-)

**Comment by rossbar** [comment]
Yes, there is indeed interest in doing so. Providing wheels for pygraphviz is a top priority for the project - unfortunately it is not straightforward. See the pinned issue #167 and related discussions on the graphviz issue tracker (e.g. [#2254](https://gitlab.com/graphviz/graphviz/-/issues/2254)) for the current sticking points.

I will go ahead and close this as duplicate as it is already being discussed in the pinned issue.
