### ISSUE TITLE
[BUG] Installation on Windows 10 fails (wheels not provided)

### ISSUE THREAD

**Issue by Kochise** [pygraphviz/pygraphviz#457]
Linking to the issue I created at `emerge` :

https://github.com/glato/emerge/issues/39

**tl;dr** : provide wheels for installing with `pip` on Windows 10 AMD64

Regards.

**Comment by MridulS** [comment]
@Kochise thanks for the opening this but it has been pretty challenging to get a working wheel for pygraphviz, we have a tracking issue https://github.com/pygraphviz/pygraphviz/issues/167 for the wheel building discussion. I'll go ahead and close this one to keep the discussion in one place. Thanks!
