### ISSUE TITLE
xlabel doesn't support html

### ISSUE THREAD

**Issue by aemxdp** [pygraphviz/pygraphviz#46]
Would be nice to make this:
```python
graph.get_node('A').attr["xlabel"] = '<<font color="purple">A</font>>'
```
being handled in same way as "label" to result in following dot:
```dot
A [xlabel=<<font color="purple">A</font>>];
```
instead of escaped:
```dot
A [xlabel="<<font color=\"purple\">A</font>>"];
```
If not familiar with feature, take a look here: http://www.graphviz.org/content/node-shapes#html

**Comment by hagberg** [comment]
I didn't even know about "xlabel'.  Try out the fix here and let me know if that works.

**Comment by aemxdp** [comment]
@hagberg I've checked out and it works fine. Thanks!
