### ISSUE TITLE
is this installable on windows? the doc instructions don't work

### ISSUE THREAD

**Issue by simonm3** [pygraphviz/pygraphviz#474]
I followed the instructions in the docs but they don't work
```
python -m pip install --use-pep517 `
              --config-setting="--global-option=build_ext" `
              --config-setting="--global-option="-IC:\Program Files\Graphviz\include" `
              --config-setting="--global-option="-LC:\Program Files\Graphviz\lib" `
              pygraphviz
```

     ERROR: Invalid requirement: 'Files\\Graphviz\\include \n--config-setting=--global-option=-LC:\\Program Files\\Graphviz\\lib'
Hint: It looks like a path. File 'Files\Graphviz\include
--config-setting=--global-option=-LC:\Program Files\Graphviz\lib' does not exist.

Found another command that does install
```
pip install --global-option=build_ext --global-option="-IC:\Program Files\Graphviz\include" --global-option="-LC:\Program Files\Graphviz\lib" pygraphviz"
```
However this gives another error when i try to import pygraphviz:

ImportError: DLL load failed while importing _graphviz: %1 is not a valid Win32 application.

**Comment by MridulS** [comment]
It looks like a mismatch between graphviz versions (32 vs 64 bit?) ? Maybe this helps https://github.com/pygraphviz/pygraphviz/issues/445#issuecomment-1347575359 ?

**Comment by simonm3** [comment]
Thanks. Yes I had python 64 bit and graphviz 64 bit but also an entry in PATH pointing to a 32 bit version! Now it works.
