### ISSUE TITLE
escaping bug: " after \ isn't correctly escaped...

### ISSUE THREAD

**Issue by joernhees** [pygraphviz/pygraphviz#48]
i have a node label containing `\"` (so a literal `\` followed by a `"`) (don't ask me why, it's real world data :-/ ...)

``` python
In [1]: from pygraphviz import *

In [2]: g = AGraph()

In [3]: g.add_edge('foo', '"bar\\"bar"')

In [4]: g.to_string()
Out[4]: u'strict graph  {\n\tfoo -- "\\"bar\\\\"bar\\"";\n}\n'

In [5]: print g.to_string()
strict graph  {
    foo -- "\"bar\\"bar\"";
}
```

In 5 you can see that the `\` is correctly escaped for dot, but the following `"` isn't and will end the node label causing the parsers to fail.

**Comment by hagberg** [comment]
Wow, backslash nightmare.  
Can you use raw python strings so Python won't convert the backslashes first?
e.g.
```python
In [1]: from pygraphviz import *

In [2]: g = AGraph()

In [3]: g.add_edge('foo', r'"bar\\"bar"')

In [4]: print g
strict graph {
	foo -- "\"bar\\\"bar\"";
}


In [5]: g.to_string()
Out[5]: u'strict graph  {\n\tfoo -- "\\"bar\\\\\\"bar\\"";\n}\n'
```

**Comment by joernhees** [comment]
hehe, well, it's in the middle of some pipeline. i'd never have entered that string myself, i just found it during debugging cause when i try to put it into some node label in pygraphviz and i try to draw the graph it throws an error because it can't parse the generated dotfile anymore...

just to make it clear:
```python
In [1]: r'"bar\\"bar"' == '"bar\\\\"bar"'
Out[1]: True

In [2]: r'"bar\"bar"' == '"bar\\"bar"'
Out[2]: True

In [3]: print '"bar\\"bar"', r'"bar\"bar"'
"bar\"bar" "bar\"bar"

In [4]: r'"bar\"bar"' == r'"bar\\"bar"'
Out[4]: False

```
I have the strings in 2 or 3, no matter how you like to write them... and i just pass them as node labels into pygraphviz... 4 shows that they're different from what you wrote

**Comment by joernhees** [comment]
where are quotes `"` in node labels escaped?

**Comment by hagberg** [comment]
I guess you'll need to either add the right number of backslashes to your strings (fun!) or maybe

In [1]: from pygraphviz import *

In [2]: g = AGraph()

In [3]: g.add_edge('foo', 'bar\\"bar'.encode('string-escape'))

In [4]: print g
strict graph {
	foo -- "bar\\\"bar";
}

![foo](https://cloud.githubusercontent.com/assets/187875/6762984/3c4499f4-cf31-11e4-9797-26e870b416d6.png)

**Comment by joernhees** [comment]
Uhm, i expected pygraphviz to care about its escaping, as otherwise it would be inconsistent with other things it correctly escapes (such as the leading and ending `"` in my first example)...

As a user of the library i expected that it hides the graphviz interna from me (such as correct graphviz specific escaping), so that i could just throw in whatever unicode string i have and it will correctly escape it as a node label. Expecting users to escape the strings themselves seems like a weird approach (you wouldn't accept a csv / json lib that asked you to please correctly escape things first, would you?)

Last but not least: The graph you printed is not what i'm after either: the lower node should say: `"bar\"bar"`.

(I'm not constructing this artificially, it's the RDF N3 representation of string Literals (`"here is an english literal"@en`) that i want to be able to distinguish from URIs (`<http://uris.are.in.brackets>`).)

**Comment by hagberg** [comment]
I won't argue that pygraphviz (or graphviz for that matter) is perfect.  

The story of graphviz strings, escapes, encodings can be found here http://www.graphviz.org/doc/info/lang.html
pygraphviz does essentially no extra handling of strings other than what either Python or Graphviz do to escape, encode, etc.  (The one exception is HTML label handling in the label and xlabel attributes).

If anyone wants to improve the string-handling to be more intuitive, fixes are welcome.   

That being said, the original issue can be solved with string-escape encoding like this

```python
In [1]: from pygraphviz import *

In [2]: g = AGraph()

In [3]: g.add_edge('foo', '"bar\\"bar"'.encode('string-escape'))

In [4]: print g
strict graph {
	foo -- "\"bar\\\"bar\"";
}
```
![foo](https://cloud.githubusercontent.com/assets/187875/6765467/01e3b7ba-cfa7-11e4-8205-1b120399951d.png)
