### ISSUE TITLE
Install on windows fails because of missing ms build tools

### ISSUE THREAD

**Issue by FTamas77** [pygraphviz/pygraphviz#481]
In the past, I faced to similar issue and I could solve it. Now, I don't remember the solution.  I have tried several post, reports, blogs... I've installed the ms build tools and the graphviz and run this command:

pip install --global-option=build_ext --global-option="-IC:\Program Files\Graphviz\include" --global-option="-LC:\Program Files\Graphviz\lib" pygraphviz

and some similar ones, for example, the official one from their website.

I have this:

`(causalityEnv) PS D:\Projects\Causality> pip install --global-option=build_ext --global-option="-IC:\Program Files\Graphviz\include" --global-option="-LC:\Program Files\Graphviz\lib" pygraphviz
DEPRECATION: --build-option and --global-option are deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option.
Collecting pygraphviz
  Using cached pygraphviz-1.11.zip (120 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pygraphviz
  Building wheel for pygraphviz (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      running build_ext
      building 'pygraphviz._graphviz' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygraphviz
  Running setup.py clean for pygraphviz
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      running build_ext
      building 'pygraphviz._graphviz' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pygraphviz
Failed to build pygraphviz
ERROR: Could not build wheels for pygraphviz, which is required to install pyproject.toml-based projects`

I also added paths to my path environment, but still there is no luck. Others suggested the administrator right, but no result.

I guess I missed an environment variable or used the wrong component/version from the build tool.

**Comment by FTamas77** [comment]
[Same issue with a different package](https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required)
I installed that package without any problem, so, I think the problem is not about the missing ms build tools, but to tell how it can find it. Is the any logging?

**Comment by rossbar** [comment]
This issue very much seems to arise from the build tool setup on specific systems; I don't think there's anything in `pygraphviz` itself that can be done to improve the situation. Currently, the only way around having to build extensions from source locally is to use the `conda-forge` distribution, which comes with graphviz pre-packaged.
