### ISSUE TITLE
Cannot install pygraphviz on MacOS with --config-setting

### ISSUE THREAD

**Issue by gotofritz** [pygraphviz/pygraphviz#490]
Mac OSX Ventura 13.4 (22F66)
Apple M1 Max Chip
Python 3.10.6, 3.11.1

Installed graphviz with `brew install graphviz`

Tried to install pygraphviz with 

```
pip install --global-option=build_ext \
            --global-option="-L/opt/lib/mygviz/" \
            --global-option="-R/opt/lib/mygviz/" \
            pygraphviz
```

Long list of alerts, and ends with

```
pygraphviz/graphviz_wrap.c:3020:10: fatal error: 'graphviz/cgraph.h' file not found
      #include "graphviz/cgraph.h"
               ^~~~~~~~~~~~~~~~~~~
      197 warnings and 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by gotofritz** [comment]
(also tried:


```
 pip install --config-setting="--global-option=build_ext" \
             --config-setting="--build-option=-I$(brew --prefix graphviz)/include/" \
             --config-setting="--build-option=-L$(brew --prefix graphviz)/lib/" \
             pygraphviz
```

**Comment by dschult** [comment]
Can you see if those files actually exist (e.g. `/opt/include/graphviz/cgraph.h`)?  
If you can find where the `cgraph.h` file exists then you can point pip to that location. Presumably the `lib` files would be close to the `include` files.

**Comment by gotofritz** [comment]
Yes it seems to be there

```
ls $(brew --prefix graphviz)/include/graphviz/cgraph.h
-rw-r--r--@ 1 fritz  admin  20975 11 Sep 20:27 /opt/homebrew/opt/graphviz/include/graphviz/cgraph.h
```

**Comment by gotofritz** [comment]
One thing I forgot to mention - I am using pyenv

I attach the full log in cast it's helpful 
[error.txt](https://github.com/pygraphviz/pygraphviz/files/13773916/error.txt)

**Comment by j-carson** [comment]
I have also had problems with installing on a mac with M1 chip -- it does not appear that the extra -I and -L options for graphviz are being passed to clang 

I have tried changing the spelling from config-setting to config-settings (as seen in one of the other issues) and replacing the $(brew --prefix graphviz) command with the absolute path to my build directory.

**Comment by gotofritz** [comment]
To be honest I have given up trying to run it on the mac directly and used a (docker) dev container in VSCode instead... works seamlessly and was easy to set up. Thanks for your help, I will close the issue unless happy to reopen it if someone else wants to get to the bottom of it.

**Comment by tdg5** [comment]
A buddy of mine was running into the same problem and for us the needed incantation was

```bash
pip install \
  --use-pep517 \
  --config-settings="--global-option=build_ext" \
  --config-settings="--global-option=-I$(brew --prefix graphviz)/include/" \
  --config-settings="--global-option=-L$(brew --prefix graphviz)/lib/" \
  pygraphviz
```

I found that `--build-option` wasn't sufficient because for some reason the additional arguments are needed when trying to figure out the requirements for the wheel, not just when running `bdist_wheel`.

Some related docs https://pip.pypa.io/en/stable/cli/pip_wheel/#cmdoption-global-option

**Comment by ashaltu** [comment]
Would be nice if docs could be updated here https://pygraphviz.github.io/documentation/stable/install.html#macos

Ran into this problem and @tdg5 solution worked

**Comment by dschult** [comment]
The latest docs have been updated here
https://pygraphviz.github.io/documentation/latest/install.html#macos 

So a new release will move those to the stable docs. We're hoping that'll happen soon.
It is very close to the solution @tdg5 suggested above (`--no-cache-dir` instead of `--use-pep517`).
But the key point of the solution is to use the `global-option` throughout if I understand correctly.
Comments and suggestions are welcome.  Thanks!

**Comment by codekiln** [comment]
The above did not work for me: 

```
!brew uninstall graphviz
!brew install graphviz
!pip install \
  --use-pep517 \
  --config-settings="--global-option=build_ext" \
  --config-settings="--global-option=-I$(brew --prefix graphviz)/include/" \
  --config-settings="--global-option=-L$(brew --prefix graphviz)/lib/" \
  pygraphviz
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygraphviz/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygraphviz/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygraphviz/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygraphviz/
Could not fetch URL https://pypi.org/simple/pygraphviz/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pygraphviz/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pygraphviz (from versions: none)
ERROR: No matching distribution found for pygraphviz
```

**Comment by dschult** [comment]
This looks like an SSL issue while trying to connect to the pypi server -- not a pygraphviz problem.
I would suggest waiting a short while and trying again. There is nothing in your command that will either cause or fix this error. It is trying to certify that pypi is serving the files and it is having trouble doing that.
