### ISSUE TITLE
Newline in node not escaped in dot output

### ISSUE THREAD

**Issue by colinhogben** [pygraphviz/pygraphviz#491]
Using version 1.11, the following code:

```py
import pygraphviz
g = pygraphviz.AGraph()
g.add_edge('test', 'two\nlines')
g.write('twolines.dot')
```
generates a file containing:
```
strict graph "" {
	test -- "two
lines";
}
```
Running `dotty` on the file then gives an error:
```
graph parser: string ran past end of line near line 2
context: two
\0t -- >>>   <<< "two
dotty.lefty: giving up on dot
```

I expected that pygraphviz would generate a valid dot file, e.g. by escaping the newline as `\n`

**Comment by dschult** [comment]
Try using `dot` on the same file. That works for me.
And I don't get `dotty` when I install graphviz 9.0.0.  
Is this only occurring for dotty? or for the other CLI tools as well?
