### ISSUE TITLE
Unable to Execute Graphviz Script in Spyder

### ISSUE THREAD

**Issue by Chrise123** [pygraphviz/pygraphviz#51]
I am unable to execute a Graphviz test script in Spyder (which is based on Python 2.7.9). The Script and the Test Result are attached. The test result shows Pygraphviz is required.

I attempted to install Pygraphviz using pip but that failed because Graphviz could not be found, but Graphviz appears to be installed in /Library/Python/2.7/site-packages. The install attempt and the contents of the /Library/Python/2.7/site-packages directory are also attached.

I am probably not installing Pygraphviz correctly and/or Graphviz is not installed correctly. I would really appreciate any help to overcome this problem.

![screen shot 2015-04-28 at 9 03 27 pm](https://cloud.githubusercontent.com/assets/12151953/7368314/1dbdfdfe-edea-11e4-964a-7c4a717e0fce.png)
![screen shot 2015-04-28 at 9 05 16 pm](https://cloud.githubusercontent.com/assets/12151953/7368363/5f4a04f2-edea-11e4-9ead-b9c3198cd147.png)
![screen shot 2015-04-28 at 9 07 35 pm](https://cloud.githubusercontent.com/assets/12151953/7368395/b3a7f130-edea-11e4-82d6-4571fd024b37.png)
![screen shot 2015-04-28 at 9 09 22 pm](https://cloud.githubusercontent.com/assets/12151953/7368411/e9dfc5b6-edea-11e4-97e4-314d7329194f.png)

**Comment by Chrise123** [comment]
Further to the above I have Graphviz working as a standalone program but am unable to execute it in the Spyder IDE because Pygraphviz is required. The final objective is to partition a particular graph using Metis and then to display the result with Graphviz.
I have tried various methods of installing Pygraphviz but all have not produced the ability to execute the test script above. Any ideas would be most welcome. If this is not the correct forum please let me know where I might try to get some help.

**Comment by mahmud1180** [comment]
Hi Chrise! Have you solved the problem? I am facing the same issue with Spyder. Please let me know if you have any solutions. Thanks

**Comment by Chrise123** [comment]
No joy! It all got too hard for me which was a big disappointment. I would appreciate hearing from you if you manage to solve the problem.
