### ISSUE TITLE
Unable to set node_attr and edge_attr correctly

### ISSUE THREAD

**Issue by cinntamani** [pygraphviz/pygraphviz#511]
I seem to have encountered a very strange yet basic issue. Once `graph_attr` is set, `node_attr` and `edge_attr` cannot be set correctly. Did I miss something?

```
ag = pgv.AGraph()
ag.graph_attr['name'] = 'G'
dict(ag.graph_attr)
ag.node_attr['name'] = 'node'
dict(ag.node_attr)
ag.edge_attr['name'] = 'edge'
dict(ag.edge_attr)
```

**Comment by dschult** [comment]
You should consult the GraphViz library for details, but I seem to recall that the default attribute handling in the libraries had (this was a while ago) a hierarchy to them. Some graph attributes applied to default values throughout the graph, I.e. for nodes and edges too. There were also strange things when default values were set after nodes are created. It is possible that those issues with the GraphViz libraries have been fixed. But your report suggests maybe not.

the good news is that it is the default attribute value system that is wonky. If you name the attributes differently in graph, edge and node there are no troubles. And you can always just set explicit node/edge attributes on all nodes/edges to bypass the default values. :)

**Comment by cinntamani** [comment]
Thank you for the explanation. You are right that if node and edge default attributes do not share keys with graph default attributes, then things work out:
```
ag = pgv.AGraph()
ag.graph_attr['rankdir'] = 'LR'
dict(ag.graph_attr)
ag.node_attr['name'] = 'node'
dict(ag.node_attr)
ag.edge_attr['name'] = 'edge'
dict(ag.edge_attr)
```

**Comment by dschult** [comment]
OK -- I'm going to close this then... 
Feel free to comment here and we'll see it (or open a new issue) if you have other comments.
