### ISSUE TITLE
installing from conda requires to change torch vision to CPU version.

### ISSUE THREAD

**Issue by Hansyvea** [pygraphviz/pygraphviz#531]
conda install --channel conda-forge pygraphviz
`
## Package Plan ##

  environment location: /home/user/miniconda3/envs/statss

  added / updated specs:
    - pygraphviz

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    atk-1.0-2.38.0             |       h04ea711_2         348 KB  conda-forge
    cairo-1.16.0               |       hb05425b_5         1.2 MB
    cloudpathlib-0.16.0        |     pyhd8ed1ab_0          37 KB  conda-forge
    expat-2.6.2                |       h59595ed_0         134 KB  conda-forge
    font-ttf-dejavu-sans-mono-2.37|       hab24e00_0         388 KB  conda-forge
    font-ttf-inconsolata-3.000 |       h77eed37_0          94 KB  conda-forge
    font-ttf-source-code-pro-2.038|       h77eed37_0         684 KB  conda-forge
    font-ttf-ubuntu-0.83       |       h77eed37_2         1.5 MB  conda-forge
    fontconfig-2.14.1          |       h4c34cd2_2         281 KB
    fonts-conda-ecosystem-1    |                0           4 KB  conda-forge
    fonts-conda-forge-1        |                0           4 KB  conda-forge
    fribidi-1.0.10             |       h36c2ea0_0         112 KB  conda-forge
    gdk-pixbuf-2.42.10         |       h5eee18b_0         600 KB
    glib-2.80.2                |       hf974151_0         586 KB  conda-forge
    glib-tools-2.80.2          |       hb6ce0ca_0         112 KB  conda-forge
    graphite2-1.3.14           |       h295c915_1          97 KB
    graphviz-2.50.0            |       h8e749b2_2         3.0 MB  conda-forge
    gtk2-2.24.33               |       h90689f9_2         7.4 MB  conda-forge
    gts-0.7.6                  |       h977cf35_4         311 KB  conda-forge
    harfbuzz-4.3.0             |       hf52aaf7_2         1.3 MB
    jpeg-9e                    |       h0b41bf4_3         235 KB  conda-forge
    libexpat-2.6.2             |       h59595ed_0          72 KB  conda-forge
    libgd-2.3.3                |       h695aa2c_1         222 KB
    libglib-2.80.2             |       hf974151_0         3.7 MB  conda-forge
    libllvm15-15.0.7           |       hadd5161_1        31.5 MB  conda-forge
    librsvg-2.54.4             |       h36cc946_3         6.0 MB
    libtool-2.4.7              |       h27087fc_0         402 KB  conda-forge
    openssl-3.3.0              |       hd590300_0         2.8 MB  conda-forge
    pango-1.50.7               |       h05da053_0         427 KB
    pcre2-10.43                |       hcad00b1_0         929 KB  conda-forge
    pillow-10.3.0              |  py310h5eee18b_0         779 KB
    pixman-0.43.2              |       h59595ed_0         378 KB  conda-forge
    pygraphviz-1.9             |  py310h5eee18b_1         136 KB
    spacy-3.7.3                |  py310hcb52e73_0         5.2 MB  conda-forge
    thinc-8.2.3                |  py310h256d06d_0         857 KB  conda-forge
    torchvision-0.15.2         |cpu_py310h83e0c9b_0         9.8 MB
    wasabi-1.1.2               |  py310hff52083_1          47 KB  conda-forge
    weasel-0.3.4               |     pyhd8ed1ab_0          42 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        81.5 MB

The following NEW packages will be INSTALLED:

  atk-1.0            conda-forge/linux-64::atk-1.0-2.38.0-h04ea711_2
  cairo              pkgs/main/linux-64::cairo-1.16.0-hb05425b_5
  cloudpathlib       conda-forge/noarch::cloudpathlib-0.16.0-pyhd8ed1ab_0
  expat              conda-forge/linux-64::expat-2.6.2-h59595ed_0
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-h77eed37_2
  fontconfig         pkgs/main/linux-64::fontconfig-2.14.1-h4c34cd2_2
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0
  fribidi            conda-forge/linux-64::fribidi-1.0.10-h36c2ea0_0
  gdk-pixbuf         pkgs/main/linux-64::gdk-pixbuf-2.42.10-h5eee18b_0
  glib               conda-forge/linux-64::glib-2.80.2-hf974151_0
  glib-tools         conda-forge/linux-64::glib-tools-2.80.2-hb6ce0ca_0
  graphite2          pkgs/main/linux-64::graphite2-1.3.14-h295c915_1
  graphviz           conda-forge/linux-64::graphviz-2.50.0-h8e749b2_2
  gtk2               conda-forge/linux-64::gtk2-2.24.33-h90689f9_2
  gts                conda-forge/linux-64::gts-0.7.6-h977cf35_4
  harfbuzz           pkgs/main/linux-64::harfbuzz-4.3.0-hf52aaf7_2
  jpeg               conda-forge/linux-64::jpeg-9e-h0b41bf4_3
  libexpat           conda-forge/linux-64::libexpat-2.6.2-h59595ed_0
  libgd              pkgs/main/linux-64::libgd-2.3.3-h695aa2c_1
  libglib            conda-forge/linux-64::libglib-2.80.2-hf974151_0
  librsvg            pkgs/main/linux-64::librsvg-2.54.4-h36cc946_3
  libtool            conda-forge/linux-64::libtool-2.4.7-h27087fc_0
  pango              pkgs/main/linux-64::pango-1.50.7-h05da053_0
  pcre2              conda-forge/linux-64::pcre2-10.43-hcad00b1_0
  pixman             conda-forge/linux-64::pixman-0.43.2-h59595ed_0
  pygraphviz         pkgs/main/linux-64::pygraphviz-1.9-py310h5eee18b_1
  thinc              conda-forge/linux-64::thinc-8.2.3-py310h256d06d_0
  wasabi             conda-forge/linux-64::wasabi-1.1.2-py310hff52083_1
  weasel             conda-forge/noarch::weasel-0.3.4-pyhd8ed1ab_0

The following packages will be REMOVED:

  libhwloc-2.9.3-default_h554bfaf_1009
  libjpeg-turbo-3.0.0-hd590300_1

The following packages will be UPDATED:

  openssl                                  3.2.1-hd590300_1 --> 3.3.0-hd590300_0
  pillow             conda-forge::pillow-10.1.0-py310h01dd~ --> pkgs/main::pillow-10.3.0-py310h5eee18b_0
  spacy              pkgs/main::spacy-3.5.3-py310h3c18c91_0 --> conda-forge::spacy-3.7.3-py310hcb52e73_0

The following packages will be SUPERSEDED by a higher-priority channel:

  lcms2                  conda-forge::lcms2-2.16-hb7c19ff_0 --> pkgs/main::lcms2-2.12-h3be6417_0
  lerc                   conda-forge::lerc-4.0.0-h27087fc_0 --> pkgs/main::lerc-3.0-h295c915_0
  libdeflate         conda-forge::libdeflate-1.19-hd590300~ --> pkgs/main::libdeflate-1.17-h5eee18b_1
  libtiff             conda-forge::libtiff-4.6.0-ha9c0a0a_2 --> pkgs/main::libtiff-4.5.1-h6a678d5_0
  libxml2            conda-forge::libxml2-2.11.6-h232c23b_0 --> pkgs/main::libxml2-2.10.4-hf1b16e4_1
  openjpeg           conda-forge::openjpeg-2.5.0-h488ebb8_3 --> pkgs/main::openjpeg-2.4.0-h3ad879b_0
  tbb                 conda-forge::tbb-2021.11.0-h00ab1b0_0 --> pkgs/main::tbb-2021.8.0-hdb19cb5_0
  torchvision        pytorch::torchvision-0.16.0-py310_cu1~ --> pkgs/main::torchvision-0.15.2-cpu_py310h83e0c9b_0

The following packages will be DOWNGRADED:

  libllvm15                               15.0.7-h5cf9203_3 --> 15.0.7-hadd5161_1
`

**Comment by rossbar** [comment]
This looks like an issue with the conda resolver... I don't know how the "The following packages will be SUPERSEDED by a higher-priority channel" mechanism works, but that seems to be the root of the problem.

I'd suggest looking into how to disable non-conda-forge channels or id'ing channel priority. Either way, this strikes me as a conda issue - I don't think there's anything the pygraphviz project can do to influence the resolver.

Closing as unrelated - feel free to post/reopen as needed if something specific to pygraphviz turns up!
