### ISSUE TITLE
[Bug] `AGraph.draw()`: File Handle not closed if `type(path)` is `pathlib.Path`

### ISSUE THREAD

**Issue by PhilippvK** [pygraphviz/pygraphviz#534]
The newer versions of Python (I am using **Python v3.10**) throws a warning that resources are allocated and not closed properly afterwards. This warning shows up when passing a `pathlib.Path` instead of a `str` to `AGraph.draw(path)`

**Error Message:**
```
/work/git/private/pygraphviz/bug.py:34: ResourceWarning: unclosed file <_io.BufferedRandom name='simple.png'>
  B.draw(pathlib.Path("simple.png"))  # draw png
````

The problem is that `pathlib.Path` is not handled in here:

https://github.com/pygraphviz/pygraphviz/blob/7d7ac92b145917a4549814f8b9bd5a054fd9376a/pygraphviz/agraph.py#L1620-L1621

**Possible Solutions:**
1. Convert `pathlib.Path` to `str` before calling `AGraph.draw()`
2. Add `pathlib.Path` to `isinstance` check: `isinstance(path, (str, pathlib.Path))` (See #535)

**Script to reproduce the error:**
```python
import pygraphviz as pgv
import pathlib

A = pgv.AGraph()

A.add_edge(1, 2)
A.add_edge(2, 3)
A.add_edge(1, 3)
A.layout()  # layout with default (neato)

A.draw("simple.png")  # no warning
A.draw(pathlib.Path("simple.png"))  # warning
A.draw(str(pathlib.Path("simple.png")))  # no warning
```

**Comment by rossbar** [comment]
FWIW I created a branch that has only the test from #534 and ran it through CI - it's not tripping up either on any platforms: https://github.com/rossbar/pygraphviz/actions/runs/10723176730

This is definitely worth chasing down, but the first step would be to track down a reliable reproducer.

**Comment by PhilippvK** [comment]
@rossbar I am using Ubuntu 20.04. However I recently moved from the APT version of Python v3.8 to Python a self-compiled version of v3.10/v3.12. I think this might explain why eventually only I was experiencing this warning (as they might be disabled for introducing less runtime overheads in optimized builds of Python which are shipped with the distributions). I am not 100% sure about my theory but it seem plausible to me.

As you pointed out, the warning is still relevant even if it does only show up for specific Python builds as unclosed resources should be avoided all the time.

**Comment by rossbar** [comment]
> I am using Ubuntu 20.04. However I recently moved from the APT version of Python v3.8 to Python a self-compiled version of v3.10/v3.12. I think this might explain why eventually only I was experiencing this warning (as they might be disabled for introducing less runtime overheads in optimized builds of Python which are shipped with the distributions). I am not 100% sure about my theory but it seem plausible to me.

FWIW I'm using a source-built Python3.10 on Fedora and am not seeing any issues... just curious if there were any obvious indicators that this was platform-specific (seems not).

> As you pointed out, the warning is still relevant even if it does only show up for specific Python builds as unclosed resources should be avoided all the time.

Agreed - it'd just be nice to know what specific code paths are causing the issue. I think your hypothesis (i.e. needing to handle pathlib objects explicitly) is a good one. It'd just be nice to have a reliable test of the behavior!

**Comment by PhilippvK** [comment]
@rossbar 
After a bit of research it I found what is different between my Python version and yours. I build (accidentally) with `--with-pydebug`. This enables debug mode, which basically clears the list of default warning filters.

By default (in non-debug mode) the following warnings are filtered:

```
default::DeprecationWarning:__main__
ignore::DeprecationWarning
ignore::PendingDeprecationWarning
ignore::ImportWarning
ignore::ResourceWarning
```

I assume that you could reproduce my results with your Python version in non-debug mode by running `python -W default …` instead of `python …`

Source: https://docs.python.org/3/library/warnings.html#the-warnings-filter
