### ISSUE TITLE
Cannot install pygraphviz

### ISSUE THREAD

**Issue by pujaarajan** [pygraphviz/pygraphviz#54]
OSError: Error locating graphviz.

Try to redownload graphviz and requirement is already satisfied.

Using Jupyter.

**Comment by hagberg** [comment]
Hopefully there is a longer error message than that.  We'll definitely need more information to figure out the issue too like versions of graphviz and pygraphviz.

**Comment by pujaarajan** [comment]
![screen shot 2015-06-01 at 3 42 52 pm](https://cloud.githubusercontent.com/assets/10352446/7922895/e62d61cc-0874-11e5-824b-44ded095a365.png)

**Comment by pujaarajan** [comment]
![screen shot 2015-06-01 at 3 43 52 pm](https://cloud.githubusercontent.com/assets/10352446/7922913/07f6296a-0875-11e5-9ea4-f5dde69eee0a.png)

**Comment by hagberg** [comment]
You need the graphviz packages from graphviz.org.   You are getting a Python package from pypi not the C/C++ language code.

It looks like you might be running Linux so try installing graphviz and graphviz-dev  (or similar) from your OS package repository.

**Comment by pujaarajan** [comment]
![screen shot 2015-06-03 at 1 13 08 pm](https://cloud.githubusercontent.com/assets/10352446/7967829/5a4c5d1e-09f2-11e5-99d8-9b1b71720701.png)

![screen shot 2015-06-03 at 1 13 45 pm](https://cloud.githubusercontent.com/assets/10352446/7967830/5e94c46a-09f2-11e5-8369-da862706df27.png)

I am sshing and then running ipython and opening a jupyter terminal. Do I need to install something like homebrew?

What is libcgraph that is not found?

**Comment by hagberg** [comment]
libcgraph is part of the graphviz package from graphviz.org.  http://graphviz.org/
You'll need to install that before you install pygraphviz.  

Note that the "graphviz" package you are installing with pip is a Python package and not the graphviz package you need from graphviz.org.

**Comment by pujaarajan** [comment]
![screen shot 2015-06-04 at 1 46 35 pm](https://cloud.githubusercontent.com/assets/10352446/7991769/378cbc8c-0ac0-11e5-8d61-501b808d0873.png)

**Comment by pujaarajan** [comment]
http://www.graphviz.org/Download..php

What do I use to download for iPython? Sorry I am new to this.

**Comment by pujaarajan** [comment]
![screen shot 2015-06-05 at 3 31 40 pm](https://cloud.githubusercontent.com/assets/10352446/8014639/0175c1f6-0b98-11e5-97ef-d1cc75af0bdd.png)

**Comment by hagberg** [comment]
You still don't have graphviz and graphviz-dev (or graphviz-devel) installed correctly.
Your yum install command above failed.

There is (confusingly) a python package called graphviz too - that is NOT what you want.

**Comment by pujaarajan** [comment]
Here I am trying it on my home computer

![screenshot 2015-06-07 22 24 25](https://cloud.githubusercontent.com/assets/10352446/8027790/3352bb20-0d64-11e5-98a5-b67490c5adc3.png)
![screenshot 2015-06-07 22 24 36](https://cloud.githubusercontent.com/assets/10352446/8027792/373b8aaa-0d64-11e5-90b0-62c33195b14b.png)

**Comment by pujaarajan** [comment]
Looks like sudo yum install graphviz worked this time however pip install pygraphviz still failed.

**Comment by pujaarajan** [comment]
Like you said yum install command above failed. Thank you for your help!

Worked doing this...
1. sudo yum install graphviz
2. sudo yum install graphviz-devel
3. pip install pygraphviz

**Comment by tigrus** [comment]
Under ubuntu: 

1. sudo apt-get install graphviz libgraphviz-dev graphviz-dev **pkg-config** 
2. pip install pygraphviz

**Comment by ncastrohub** [comment]
@tigrus your answer work for me.

**Comment by GiovanniBalestrieri** [comment]
Solved using `sudo apt-get install graphviz-dev`

**Comment by GaganaB** [comment]
`conda install pygraphviz` works too!
