### ISSUE TITLE
Error when using pygraphviz within gevents environment

### ISSUE THREAD

**Issue by richtera** [pygraphviz/pygraphviz#56]
When executing with patched subprocess file handles as stdin come in as FileObjectPosix wrapped around a SocketAdapter when calling layout().
These kind of file object are correctly writable and readable, but agwrite throws an error saying it's not a file handle. It seems to almost be a python problem because you're using PyFile_Check but I am looking for a workaround. Not sure exactly why layout needs to read stdin even though it has no input file.

**Comment by hagberg** [comment]
The method for computing the layout writes and reads a file.  This is definitely not optimal.  
It should be possible to avoid all of the file handling done by graphviz and do the layout and rendering completely in memory.   If someone is interested maybe start by looking at the graphviz libgvc.

**Comment by richtera** [comment]
The current workaround I am using is as follows:
```python
import pygraphviz as pgv

class AGraph(pgv.AGraph):
    """Subclass to patch write"""

    def __init__(self, *args, **kwargs):
        """Call normal initializer"""

        pgv.AGraph.__init__(self, *args, **kwargs)

    def write(self, fh):
        """Override write to make it a real file handle"""

        import types
        if not isinstance(fh, types.FileType):
            import tempfile
            nfh = tempfile.TemporaryFile('w+b')
            val = None
            try:
                val = pgv.AGraph.write(self, nfh)
            except:
                pass
            nfh.seek(0)
            fh.write(nfh.read())
            return val
        return pgv.AGraph.write(self, fh)
```

Then use AGraph instead of pgv.AGraph. It's UGLY, but it works for now.

**Comment by bbenne10** [comment]
We're running into this exact same problem. @richtera's solution seems to work around the issue perfectly, though we've simplified the code to use a context manager for `nfh` and call `super(AGraph, self)` rather than `pgv.AGraph`. 

I hate these types of comments, but :+1:.

**Comment by hagberg** [comment]
I'd like to just avoid the file issue completely - handle it correctly from python and pass the data to graphviz.  See #42
