### ISSUE TITLE
AGraph.add_node with arbitrary node attributes

### ISSUE THREAD

**Issue by jdrudolph** [pygraphviz/pygraphviz#57]
Since `n` is an argument name of `add_node` it can not be used as a keyword argument leading to an exception being thrown.

```
G = nx.Graph()
G.add_node(1, attr_dict={'n' : 10})
nx.to_agraph(G)

TypeError: add_node() got multiple values for argument 'n'
```

see networkx/networkx#1582 and networkx/networkx#1583.

Changing the signature to `add_node(self, n, attr_dict=None, **attr)` would allow for a similar behavior as in `networkx`.

Given a design decision I would be willing to contribute the necessary changes.

**Comment by dilawar** [comment]
I just ran into this bug. I am using dot as underlying description language in my application. Pygraphviz should allow using n as argument. The default `n` could be renamed `__n__`.

**Comment by hagberg** [comment]
You can also add an attribute after adding the node.
