### ISSUE TITLE
Value of strict in constructor is ignored when AGraph is created - Python 2.7

### ISSUE THREAD

**Issue by jonathanrainer** [pygraphviz/pygraphviz#59]
Using 1.3rc2 on Python 2.7 it seems that the value of strict is never set when an AGraph is constructed. 

Example:

```python
>> x = AGraph(strict=False)
>> x.strict
True
```
Is this just an oversight on my part or have I missed something really obvious about why this should be the intended behaviour?

**Comment by hagberg** [comment]
I'd guess there is something wrong with your installation.
It works for me
```
$ python -c "import pygraphviz; print pygraphviz.__version__; G = pygraphviz.AGraph(strict=False); print G.strict"
1.3rc2
False
$ dot -V
dot - graphviz version 2.36.0 (20140111.2315)
```

Maybe try running the tests?
```
$ python setup_egg.py test
```
