### ISSUE TITLE
pip install pygraphviz Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by scls19fr** [pygraphviz/pygraphviz#60]
Hello,

I'm trying to 

   pip install pygraphviz 

but it raises

    SyntaxError: Missing parentheses in call to 'print'

I'm using Anaconda Python 3 under Mac OS X

    $ python --version
    Python 3.4.3 :: Anaconda 2.3.0 (x86_64)

I had a look at Travis https://travis-ci.org/pygraphviz/pygraphviz
it seems that it's working on Python 3.4 (but maybe pip package is not up to date)

you might rename README.txt to README.md or .rst and add a badge using

    [![Build Status](https://travis-ci.org/pygraphviz/pygraphviz.svg?branch=master)](https://travis-ci.org/pygraphviz/pygraphviz)

or

    .. image:: https://travis-ci.org/pygraphviz/pygraphviz.svg?branch=master
        :target: https://travis-ci.org/pygraphviz/pygraphviz

Kind regards

**Comment by xmnlab** [comment]
Hi @scls19fr,

Other confusion information about that is in the install file:

https://github.com/pygraphviz/pygraphviz/blob/master/INSTALL.txt

    There says: PyGraphviz does not work with Python 3

**Comment by hagberg** [comment]
Hi - Thanks for the comments.  I updated the INSTALL.txt to reflect the
correct information that pygraphviz works with Python3.

Also the pip install does work from the master repository so the print
issue is resolved and will be part of the next release.
pip3 install  git+git://github.com/pygraphviz/pygraphviz.git

Aric

**Comment by xmnlab** [comment]
Thank you!

**Comment by massoudTheDude** [comment]
I had this same issue. However, running 
`pip install git+git://github.com/pygraphviz/pygraphviz.git`

caused 
```
error: command 'gcc' failed with exit status 1/usr/bin/ld: cannot find -lpython3.4m
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
```

I downloaded pygraphviz-1.3rc2.tar.gz from the [pip website](https://pypi.python.org/pypi/pygraphviz) and it installed fine.

and running pip install /path/to/pygraphviz-1.3rc2.tar.gz

**Comment by scls19fr** [comment]
Thanks
