### ISSUE TITLE
On Ubuntu 12.04: _graphviz.so: undefined symbol: Agundirected

### ISSUE THREAD

**Issue by elistevens** [pygraphviz/pygraphviz#71]
I've done the following on my dev hosts for a while now. I needed to bring up pygraphviz on a somewhat-freshly imaged host, and got a new error that I've not seen before when I tried to import (see last output; install seems to be smooth):

$ dpkg -s graphviz-dev
Package: graphviz-dev
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 90
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: graphviz
Version: 2.26.3-10ubuntu1.2
Depends: libgraphviz-dev

v$ pip install pygraphviz
Downloading/unpacking pygraphviz
  Downloading pygraphviz-1.3.1.tar.gz (103kB): 103kB downloaded
  Running setup.py (path:/home/elis/venv/mobius3d_dev/build/pygraphviz/setup.py) egg_info for package pygraphviz
    
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz
    Trying pkg-config
    include_dirs=/usr/include/graphviz
    library_dirs=
    
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
    building 'pygraphviz._graphviz' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/graphviz -I/usr/include/python2.7 -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-2.7/pygraphviz/graphviz_wrap.o
    pygraphviz/graphviz_wrap.c: In function ‘agattr_label’:
    pygraphviz/graphviz_wrap.c:3321:5: warning: return makes integer from pointer without a cast [enabled by default]
    pygraphviz/graphviz_wrap.c: In function ‘_wrap_agread’:
    pygraphviz/graphviz_wrap.c:3408:9: warning: unused variable ‘mode1’ [-Wunused-variable]
    pygraphviz/graphviz_wrap.c:3407:13: warning: unused variable ‘mode_byte_obj1’ [-Wunused-variable]
    pygraphviz/graphviz_wrap.c:3406:13: warning: unused variable ‘mode_obj1’ [-Wunused-variable]
    pygraphviz/graphviz_wrap.c:3405:7: warning: unused variable ‘fd1’ [-Wunused-variable]
    pygraphviz/graphviz_wrap.c: In function ‘_wrap_agwrite’:
    pygraphviz/graphviz_wrap.c:3466:9: warning: unused variable ‘mode2’ [-Wunused-variable]
    pygraphviz/graphviz_wrap.c:3465:13: warning: unused variable ‘mode_byte_obj2’ [-Wunused-variable]
    pygraphviz/graphviz_wrap.c:3464:13: warning: unused variable ‘mode_obj2’ [-Wunused-variable]
    pygraphviz/graphviz_wrap.c:3463:7: warning: unused variable ‘fd2’ [-Wunused-variable]
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/pygraphviz/graphviz_wrap.o -L -lcgraph -lcdt -o build/lib.linux-x86_64-2.7/pygraphviz/_graphviz.so
Successfully installed pygraphviz
Cleaning up...

$ python -c 'import pygraphviz'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/elis/venv/mobius3d_dev/local/lib/python2.7/site-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/home/elis/venv/mobius3d_dev/local/lib/python2.7/site-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/home/elis/venv/mobius3d_dev/local/lib/python2.7/site-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/home/elis/venv/mobius3d_dev/local/lib/python2.7/site-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
ImportError: /home/elis/venv/mobius3d_dev/local/lib/python2.7/site-packages/pygraphviz/_graphviz.so: undefined symbol: Agundirected

**Comment by mmarkov** [comment]
It looks like pygraphviz can not find dynamically loading libcgraph. 
Could you please try and let results:
        pkg-config --libs-only-L libcgraph
        pkg-config --cflags-only-I libcgraph

**Comment by elistevens** [comment]
Here's what I get for those two:
```
$ pkg-config --libs-only-L libcgraph
 
$ pkg-config --cflags-only-I libcgraph
-I/usr/include/graphviz  
```

Is the `-L` issue a problem on the pygraphviz side of things, or Ubuntu? My LD_LIBRARY_PATH isn't particularly interesting:

```
LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/computeprof/bin:/usr/lib/nvidia-current
```

**Comment by mmarkov** [comment]
@elistevens, for some reasons auto detecting graphviz library and include files is not perfect on ubuntu. I will try to implement something better soon. 
In meantime you may specify path to lib and include directly in command line and it should work:
```
pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
```

**Comment by elistevens** [comment]
That worked for me. Thanks!

**Comment by mmarkov** [comment]
You are welcome! I will take a look how better to auto detect path to libs or crash on install with meaningful message.

**Comment by mmarkov** [comment]
@hagberg, I implemented slightly improved graphviz locating routine in #73. Please take a look and merge.

**Comment by grahamc** [comment]
This issue is also present in debian jessie.

**Comment by mmarkov** [comment]
Did you try direct path in install option? Did it help?

I actually contributed pull request which fix it - I would appreciate if
you could try it ( see open pull requests )

**Comment by squeral** [comment]
The direct path option worked for me @mmarkov . Thank you!

**Comment by reutsharabani** [comment]
`pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"`

worked for me as well. Thanks!

**Comment by koniiiik** [comment]
Another workaround is to install pkgconf instead of pkg-config; pkgconf seems to print out a correct flag, and everything links properly:
```
$ pkg-config --libs-only-L libcgraph
-L/usr/lib  
```

**Comment by koniiiik** [comment]
Okay, I just encountered the same issue on SLES11SP3, where there is no pkgconf package available, so I did some digging.

The issue here is that the pygraphviz setup scripts expects pkg-config to always output *some* library directory when libcgraph is installed. However, pkg-config disagrees with this, and specifically implements checks that remove any default system library directories from its output; you can see that at https://cgit.freedesktop.org/pkg-config/tree/pkg.c?id=87152c05be88ca8be71a3a563f275b3686d32c28#n876 down to the end of that function.

I can see two lazy ways to fix this: either run pkg-config with the `PKG_CONFIG_ALLOW_SYSTEM_LIBS` environment variable set, which disables this pruning of system directories, or handle the case where the package is found, but does not require any `-L<dir>` flag.

I implemented the second option, i.e. allowing empty libdirs, in #89; this makes pygraphviz install correctly on SLES.

In the meantime, another easy way out is to run pip with the right pkg-config environment variable:

    PKG_CONFIG_ALLOW_SYSTEM_LIBS=OHYESPLEASE pip install pygraphviz

**Comment by hagberg** [comment]
Thanks for digging into this and providing the fix.

**Comment by urzds** [comment]
Thanks for figuring this out. I just ran into the same issue on Ubuntu 14.04.4. Would be great to have a point release with this fix. :)

**Comment by arpheno** [comment]
Just FYI, with this bug in place, it makes it prohibitively difficult for a non-professional to ever use your library.

**Comment by grahamc** [comment]
Hi Sebastian,

I know we're all a bit frustrated by this issue and wish it were fixed.
Unfortunately it can be really tough for people to devote time to open
source issues.

I'd like to encourage you to try and remain positive and supportive of this
and all the free software around, bugs and all.

Best,
Graham

**Comment by Aljumiliy1** [comment]
Hi All,
I have the same problem with installing pygraphviz.
I have tried all the solutions mentioned here but didn't work.

you can see the error below when I import it in python3. 


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /usr/local/lib/python3.4/dist-packages/pygraphviz/_graphviz.cpython-34m.so: undefined symbol: Agundirected


Thanks in advance,

Ahmed

**Comment by brchiu** [comment]
@Aljumiliy1  please see https://github.com/pygraphviz/pygraphviz/issues/115#issuecomment-344800405

**Comment by pvalsecc** [comment]
I've solved the problem with:
```shell
apt install python3-pkgconfig
```
