### ISSUE TITLE
Pkg-config-discovered graphviz include directory is incorrect on OS X 10.11 with a homebrew-installed graphviz

### ISSUE THREAD

**Issue by tom-hd** [pygraphviz/pygraphviz#77]
Installing pygraphviz using pip on OS X 10.11 using a homebrew-installed graphviz fails with the following error.

```
    clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/graphviz/2.38.0/include/graphviz -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pygraphviz/graphviz_wrap.c -o build/temp.macosx-10.11-x86_64-2.7/pygraphviz/graphviz_wrap.o
pygraphviz/graphviz_wrap.c:2954:10: fatal error: 'graphviz/cgraph.h' file not found
#include "graphviz/cgraph.h"
```

This appears to be the same error that is being addressed in https://github.com/pygraphviz/pygraphviz/pull/73 with an Ubuntu-specific alternative to the automatic include-path discovery.

The discovery logic using `pkg-config` results in the following include path being found.

```
$ pkg-config --cflags-only-I libcgraph
-I/usr/local/Cellar/graphviz/2.38.0/include/graphviz
```

However the actual header file referenced in `pygraphviz_wrap.c` is at `/usr/local/Cellar/graphviz/2.38.0/include/graphviz/cgraph.h`, so the include directive `#include "graphviz/cgraph.h"` will fail (whereas I assume `#include "cgraph.h"` would be OK).

I do not know what affect the various solution that spring to mind (e.g. changing the include directive in `pygraphviz_wrap.c`; or checking that the auto-discovered include path actually contains the header files with an appropriate relative path and trying to strip the base directory from the path, if not) might have on installations for other platforms, so am hesitant to suggest a fix without discussion of the issue.

**Comment by jamesscottbrown** [comment]
> whereas I assume #include "cgraph.h" would be OK

I `git clone`d this repo, tried to install using `python setup.py install`, and got the same error. Manually making this edit enables the module the succesfully install.

However, I don't want to submit a pull request as (like you) I'm unsure if it will break things on other platforms.

**Comment by whartonlearninglab** [comment]
I successfully used this work around to pip install pygraphviz:
    cd /usr/local/Cellar/graphviz/2.38.0/include/graphviz/
    mkdir graphviz
    cp cgraph.h graphviz/

**Comment by stantonk** [comment]
@whartonlearninglab still no dice for me :(

**Comment by pdworzynski** [comment]
In the same spirit as the previous workaround by @whartonlearninglab one can do: 
```
cd  /usr/local/Cellar/graphviz/2.38.0/include/graphviz
ln -s ../graphviz
```

**Comment by mrallen1** [comment]
Thanks @pdworzynski - that worked for me too.
