### ISSUE TITLE
Using HTML-like label for node results in syntax error (due to missing quotes)

### ISSUE THREAD

**Issue by mapio** [pygraphviz/pygraphviz#79]
Using [HTML-like labels](http://www.graphviz.org/content/html-label-dot) for example as

```
import pygraphviz as pgv
gv = pgv.AGraph()
gv.add_node( 0, label='<I>a</I>')
gv.write( 'g.dot' )
```

results in the dotfile

```
 strict graph  {
    node [label="\N"];
    0    [label=<I>a</I>];
 }
```

that contains a syntax error due to the fact that the node label is note enclosed in quotes.

**Comment by hagberg** [comment]
For graphviz to interpret HTML you need to add an extra <>

```
label='<<I>a</I>>'
```

**Comment by mapio** [comment]
You are right. Even quoted `"<I>a</I>"` does not render as expected, while your suggested works perfectly. Sorry for missing the point, and thank you for your answer!
