### ISSUE TITLE
Error installing on Windows 10

### ISSUE THREAD

**Issue by aewhatley** [pygraphviz/pygraphviz#80]
I tried installing pygraphviz with pip, and got the following error message:

C:\Users\Alexander>pip install pygraphviz
Collecting pygraphviz
  Downloading pygraphviz-1.3.1.tar.gz (103kB)
    100% |################################| 106kB 2.6MB/s
Building wheels for collected packages: pygraphviz
  Running setup.py bdist_wheel for pygraphviz
  Complete output from command C:\Users\Alexander\Anaconda3\python.exe -c "impor
t setuptools;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pip-build-ww60
_xev\\pygraphviz\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '
\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\ALEXAN~1\AppData\Local\Temp\tm
p2s4r_b1qpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\agraph.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\release.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\version.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\__init__.py -> build\lib.win-amd64-3.5\pygraphviz
  creating build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.5\pygraph
viz\tests
  copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.5
\pygraphviz\tests
  copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.5\pygraphviz\t
ests
  copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.5\pygraphviz
\tests
  copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.5\py
graphviz\tests
  copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.5\pygraphviz\t
ests
  copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.5\pygraphviz\te
sts
  copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.5\pygraphviz\
tests
  copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.5\py
graphviz\tests
  copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.5\pygraphv
iz\tests
  copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.5\pygraphviz\
tests
  copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.5\pygraphvi
z\tests
  copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.5\pygraphviz
\tests
  copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.5\pygraphviz\tes
ts
  running egg_info
  writing dependency_links to pygraphviz.egg-info\dependency_links.txt
  writing top-level names to pygraphviz.egg-info\top_level.txt
  writing pygraphviz.egg-info\PKG-INFO
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*~' found anywhere in distribu
tion
  warning: no previously-included files matching '*.pyc' found anywhere in distr
ibution
  warning: no previously-included files matching '.svn' found anywhere in distri
bution
  no previously-included directories found matching 'doc\build'
  writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
  copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.5\pygraphviz
  running build_ext
  building 'pygraphviz._graphviz' extension
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  creating build\temp.win-amd64-3.5\Release\pygraphviz
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /no
logo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Alexander\Anaconda3\include -IC:\Users\
Alexander\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14
.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\
INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt" "-
IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Fi
les (x86)\Windows Kits\10\include\10.0.10586.0\shared" "-IC:\Program Files (x86)
\Windows Kits\10\include\10.0.10586.0\um" "-IC:\Program Files (x86)\Windows Kits
\10\include\10.0.10586.0\winrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-
amd64-3.5\Release\pygraphviz/graphviz_wrap.obj
  graphviz_wrap.c
  pygraphviz/graphviz_wrap.c(2954): fatal error C1083: Cannot open include file:
 'graphviz/cgraph.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN
\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pygraphviz
Failed to build pygraphviz
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz
    Complete output from command C:\Users\Alexander\Anaconda3\python.exe -c "imp
ort setuptools, tokenize;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pi
p-build-ww60_xev\\pygraphviz\\setup.py';exec(compile(getattr(tokenize, 'open', o
pen)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --recor
d C:\Users\ALEXAN~1\AppData\Local\Temp\pip-crmyxkps-record\install-record.txt --
single-version-externally-managed --compile:
    running install
    include_dirs=None
    library_dirs=None
    running build
    running build_py
    running egg_info
    writing top-level names to pygraphviz.egg-info\top_level.txt
    writing pygraphviz.egg-info\PKG-INFO
    writing dependency_links to pygraphviz.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*~' found anywhere in distri
bution
    warning: no previously-included files matching '*.pyc' found anywhere in dis
tribution
    warning: no previously-included files matching '.svn' found anywhere in dist
ribution
    no previously-included directories found matching 'doc\build'
    writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
    running build_ext
    building 'pygraphviz._graphviz' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /
nologo /Ox /W3 /GL /DNDEBUG /MD -INone -IC:\Users\Alexander\Anaconda3\include -I
C:\Users\Alexander\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual
Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\V
C\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0
\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\P
rogram Files (x86)\Windows Kits\10\include\10.0.10586.0\shared" "-IC:\Program Fi
les (x86)\Windows Kits\10\include\10.0.10586.0\um" "-IC:\Program Files (x86)\Win
dows Kits\10\include\10.0.10586.0\winrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\
temp.win-amd64-3.5\Release\pygraphviz/graphviz_wrap.obj
    graphviz_wrap.c
    pygraphviz/graphviz_wrap.c(2954): fatal error C1083: Cannot open include fil
e: 'graphviz/cgraph.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\Alexander\Anaconda3\python.exe -c "import setuptools, tokenize
;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pip-build-ww60_xev\\pygrap
hviz\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().re
place('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\ALEXAN~1\AppD
ata\Local\Temp\pip-crmyxkps-record\install-record.txt --single-version-externall
y-managed --compile" failed with error code 1 in C:\Users\ALEXAN~1\AppData\Local
\Temp\pip-build-ww60_xev\pygraphviz

What is causing this problem?

**Comment by evilerliang** [comment]
look #40 for help.
