### ISSUE TITLE
Error: syntax error in line 36 near

### ISSUE THREAD

**Issue by sandrotosi** [pygraphviz/pygraphviz#83]
Hello,
running tests for pygraphviz 1.3.1 I got this "warning", as it doesnt make the test fail:

```
pygraphviz.tests.test_string.test_bad_dot_input ... Error: syntax error in line 36 near ''
ok
```

would be great to fix it

**Comment by hagberg** [comment]
OK, very late comment... This is ok - we are testing what happens with a bad input file and checking that it makes an error.  Which is a passing test for us.
