### ISSUE TITLE
Please add preferred citation (if any).

### ISSUE THREAD

**Issue by 4c656554** [pygraphviz/pygraphviz#90]
I have used pygraphviz for an academic paper. Is there a preferred citation for pygraphviz?

**Comment by hagberg** [comment]
Thanks for asking.  There is no paper publication so you can cite the web page at pygraphivz.github.io, authors http://pygraphviz.github.io/documentation/pygraphviz-1.3rc1/reference/legal.html

**Comment by carissableker** [comment]
Perhaps you can create a Zenodo DOI? 
https://zenodo.org/record/45042#.ZGeJPNJBwfk
