### ISSUE TITLE
Cannot draw self-loop in a graph

### ISSUE THREAD

**Issue by litaotju** [pygraphviz/pygraphviz#91]
I found no features to draw self-loop in a graph. So I wanna to ask that this feature should be provided by pygraphviz? or there is no feature like this in graphviz originnally?

**Comment by hagberg** [comment]
You can draw self loops.  See http://stackoverflow.com/questions/12896565/graphviz-how-do-i-make-edges-not-cross-each-other-choose-self-loop-egde-posit
for some interesting info.
