### ISSUE TITLE
OSError when calling draw

### ISSUE THREAD

**Issue by jsphon** [pygraphviz/pygraphviz#97]
I am running some Python code to draw graphs.

My Python version is:

```
Python 3.5.2 |Anaconda 4.1.1 (32-bit)| (default, Jul  2 2016, 17:49:02) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```

The code runs in PyCharm (from a unit test, or if I paste it into the console), but not from a Jupyter notebook or if I paste it into IPython.

The code is:

```
from IPython.display import SVG
import pygraphviz as pgv
from IPython.display import display

G = pgv.AGraph(directed=True)

G = pgv.AGraph(compound=True,directed=True)

sub = G.add_subgraph( name='cluster_1', label='Restaurant Open', rank='same')

sub.add_node( 'initial', label='')
sub.add_node('Loitering')
sub.add_edge('initial','Loitering')

fn = '/tmp/state.svg'

G.draw(fn, prog='dot')
display(SVG(fn))
```

The error is:
    ---------------------------------------------------------------------------
    OSError                                   Traceback (most recent call last)
    <ipython-input-3-911ea5f39626> in <module>()
    ----> 1 display_machine(receptionist)

```
/home/jon/PycharmProjects/StateMachine/state_machine/diagrams.py in display_machine(machine, filename)
    151     G = draw_machine(machine)
    152     print( 'Saving to %s'%filename)
--> 153     G.draw(filename, prog='dot')
    154     display(SVG(filename))
    155 

/home/jon/anaconda3/lib/python3.5/site-packages/pygraphviz/agraph.py in draw(self, path, format, prog, args)
   1472             args = ' '.join([args, "-T" + format])
   1473 
-> 1474         data = self._run_prog(prog, args)
   1475 
   1476         if path is not None:

/home/jon/anaconda3/lib/python3.5/site-packages/pygraphviz/agraph.py in _run_prog(self, prog, args)
   1333 
   1334         if not data:
-> 1335             raise IOError(b"".join(errors))
   1336 
   1337         if len(errors) > 0:

OSError: b'/home/jon/anaconda3/bin/dot: error while loading shared libraries: libexpat.so.0: cannot open shared object file: No such file or directory\n'
```

Why would the code only fail when running from Jupyter or an IPython console? I am using the same Python version this time.

**Comment by jsphon** [comment]
I checked the paths. In PyCharm, my path is 

    In[6]: import os
    In[7]: os.environ['PYTHONPATH'].split(os.pathsep)
    Out[7]: 
    ['/home/jon/PycharmProjects/StateMachine',
     '/home/jon/apps/pycharm-community-2016.1.4/helpers/pydev']

In IPython, my path is:

    ['',
     '/home/jon/PycharmProjects/BetfairServerBot/src',
     '/home/jon/PycharmProjects/StateMachine/']

So I updated my IPython path using

    path = '/home/jon/apps/pycharm-community-2016.1.4/helpers/pydev'
    if path not in os.environ["PATH"]:
        print( 'Appending %s to path'%path )
        os.environ["PATH"] += os.pathsep + path

However, that did not help.

**Comment by dschult** [comment]
The error you are getting indicates that the program dot is not able to
find the shared libraries.
Perhaps your python version is the same but dot is different...?

**Comment by jsphon** [comment]
Both Python versions are running on the same machine, so I'm not sure why they would behave differently.

Debugging the failed version, it Python is trying to find dot in:

    /home/jon/anaconda3/bin/dot

The successful version is looking for dot in

    /usr/bin/dot

Looking further, it is because in Pycharm, os.environ['PATH'] is

    /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:~/anaconda3/bin

Whereas in IPython, the path is

    ~/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

i.e. IPython has ~/anacoda3/bin at the front, rather than at the end.

This affects the _which method in agraph.py, which scans through the paths searching for 'dot'. I have a 'dot' in both ~/anaconda3/bin and /usr/bin/. But the 'dot' is broken in ~/anaconda/bin.

So my fix was to put the ~/anaconda3/bin at the end of the path. Perhaps _which should contain a check to see if dot exists in multiple places. If it does, a warning could be thrown.
