### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by papachoco** [pygraphviz/pygraphviz#98]
I know pygraphviz runs now on pypy.. I was wondering if there is an ETA for a new release. It has been almost a year w/o a new release.

Thanks a lot

Carlos

**Comment by ankostis** [comment]
Any news on that?

Kudos to your efforts.

**Comment by hagberg** [comment]
I think we are getting close to a release after a long delay.  We need to update some documentation and make sure there are no blocker issues.

**Comment by hagberg** [comment]
Try pygraphviz-1.4rc1 with pypy and let me know if it works for you.

**Comment by jakirkham** [comment]
Any news on 1.4 final?

**Comment by PanderMusubi** [comment]
Please, release 1.4 or 1.4rc2 with the latest merged pull requests.
