### ISSUE TITLE
Installation issue on Windows 10

### ISSUE THREAD

**Issue by Mulugruntz** [pygraphviz/pygraphviz#99]
Hi,

I've got an issue when installing pygraphviz on Windows 10.

When I try installing it with pip :

> C:\Users\Mulugruntz>pip install pygraphviz
> Collecting pygraphviz
>   Using cached pygraphviz-1.3.1.zip
> Building wheels for collected packages: pygraphviz
>   Running setup.py bdist_wheel for pygraphviz ... error
>   Complete output from command d:\python\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mulugr~1\appdata\local\temp\pip-build-adakoh\pygraphviz\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d c:\users\mulugr~1\appdata\local\temp\tmpnvuicspip-wheel- --python-tag cp27:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-2.7
>   creating build\lib.win-amd64-2.7\pygraphviz
>   copying pygraphviz\agraph.py -> build\lib.win-amd64-2.7\pygraphviz
>   copying pygraphviz\graphviz.py -> build\lib.win-amd64-2.7\pygraphviz
>   copying pygraphviz\release.py -> build\lib.win-amd64-2.7\pygraphviz
>   copying pygraphviz\version.py -> build\lib.win-amd64-2.7\pygraphviz
>   copying pygraphviz__init__.py -> build\lib.win-amd64-2.7\pygraphviz
>   creating build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   copying pygraphviz\tests__init__.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>   running egg_info
>   writing pygraphviz.egg-info\PKG-INFO
>   writing top-level names to pygraphviz.egg-info\top_level.txt
>   writing dependency_links to pygraphviz.egg-info\dependency_links.txt
>   warning: manifest_maker: standard file '-c' not found
> 
>   reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
>   reading manifest template 'MANIFEST.in'
>   warning: no previously-included files matching '_~' found anywhere in distribution
>   warning: no previously-included files matching '_.pyc' found anywhere in distribution
>   warning: no previously-included files matching '.svn' found anywhere in distribution
>   no previously-included directories found matching 'doc\build'
>   writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
>   copying pygraphviz\graphviz.i -> build\lib.win-amd64-2.7\pygraphviz
>   copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-2.7\pygraphviz
>   running build_ext
>   building 'pygraphviz._graphviz' extension
>   error: [Error 2] The system cannot find the file specified
> ---
> 
>   Failed building wheel for pygraphviz
>   Running setup.py clean for pygraphviz
> Failed to build pygraphviz
> Installing collected packages: pygraphviz
>   Running setup.py install for pygraphviz ... error
>     Complete output from command d:\python\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mulugr~1\appdata\local\temp\pip-build-adakoh\pygraphviz\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\mulugr~1\appdata\local\temp\pip-vjyxdr-record\install-record.txt --single-version-externally-managed --compile:
>     running install
>     include_dirs=None
>     library_dirs=None
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-2.7
>     creating build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\agraph.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\graphviz.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\release.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\version.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz__init__.py -> build\lib.win-amd64-2.7\pygraphviz
>     creating build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests__init__.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     running egg_info
>     writing pygraphviz.egg-info\PKG-INFO
>     writing top-level names to pygraphviz.egg-info\top_level.txt
>     writing dependency_links to pygraphviz.egg-info\dependency_links.txt
>     warning: manifest_maker: standard file '-c' not found
> 
> ```
> reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '*~' found anywhere in distribution
> warning: no previously-included files matching '*.pyc' found anywhere in distribution
> warning: no previously-included files matching '.svn' found anywhere in distribution
> no previously-included directories found matching 'doc\build'
> writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
> copying pygraphviz\graphviz.i -> build\lib.win-amd64-2.7\pygraphviz
> copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-2.7\pygraphviz
> running build_ext
> building 'pygraphviz._graphviz' extension
> error: [Error 2] The system cannot find the file specified
> 
> ----------------------------------------
> ```
> 
> Command "d:\python\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mulugr~1\appdata\local\temp\pip-build-adakoh\pygraphviz\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\mulugr~1\appdata\local\temp\pip-vjyxdr-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\mulugr~1\appdata\local\temp\pip-build-adakoh\pygraphviz\

And when I try some extra flags:

> C:\Users\Mulugruntz>pip install pygraphviz --install-option="--include-path=D:\Graphviz\include" --install-option="--library-path=D:\Graphviz\lib\release\lib"
> d:\python\lib\site-packages\pip\commands\install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
>   cmdoptions.check_install_build_global(options)
> Collecting pygraphviz
>   Using cached pygraphviz-1.3.1.zip
> Skipping bdist_wheel for pygraphviz, due to binaries being disabled for it.
> Installing collected packages: pygraphviz
>   Running setup.py install for pygraphviz ... error
>     Complete output from command d:\python\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mulugr~1\appdata\local\temp\pip-build-zb1cov\pygraphviz\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\mulugr~1\appdata\local\temp\pip-kpne_l-record\install-record.txt --single-version-externally-managed --compile --include-path=D:\Graphviz\include --library-path=D:\Graphviz\lib\release\lib:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-2.7
>     creating build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\agraph.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\graphviz.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\release.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz\version.py -> build\lib.win-amd64-2.7\pygraphviz
>     copying pygraphviz__init__.py -> build\lib.win-amd64-2.7\pygraphviz
>     creating build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     copying pygraphviz\tests__init__.py -> build\lib.win-amd64-2.7\pygraphviz\tests
>     running egg_info
>     writing pygraphviz.egg-info\PKG-INFO
>     writing top-level names to pygraphviz.egg-info\top_level.txt
>     writing dependency_links to pygraphviz.egg-info\dependency_links.txt
>     warning: manifest_maker: standard file '-c' not found
> 
> ```
> reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '*~' found anywhere in distribution
> warning: no previously-included files matching '*.pyc' found anywhere in distribution
> warning: no previously-included files matching '.svn' found anywhere in distribution
> no previously-included directories found matching 'doc\build'
> writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
> copying pygraphviz\graphviz.i -> build\lib.win-amd64-2.7\pygraphviz
> copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-2.7\pygraphviz
> running build_ext
> building 'pygraphviz._graphviz' extension
> error: [Error 2] The system cannot find the file specified
> 
> ----------------------------------------
> ```
> 
> Command "d:\python\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mulugr~1\appdata\local\temp\pip-build-zb1cov\pygraphviz\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\mulugr~1\appdata\local\temp\pip-kpne_l-record\install-record.txt --single-version-externally-managed --compile --include-path=D:\Graphviz\include --library-path=D:\Graphviz\lib\release\lib" failed with error code 1 in c:\users\mulugr~1\appdata\local\temp\pip-build-zb1cov\pygraphviz\

The error message is slightly shorter. Not sure it's a good thing or a bad one, though.

I've tried installing it through pip+git, easy_install, pip+whl, modifying the setup.py (but it cannot import "release"). None worked.
When putting the sources directly into site-packages, it manages to import it but fail just later, as it cannot import _graphviz.

I've added to the system Path variable:
D:\Graphviz\include\graphviz
and D:\Graphviz\bin
Then, D:\Graphviz\include\ and D:\Graphviz\bin and D:\Graphviz\lib\release\lib
None worked.

Any ideas?
Anyone already encountered that?

Thanks in advance :)

**Comment by alby3z** [comment]
You probably don't have the C++ compiler installed on your pc, go to the following site:

[http://landinghub.visualstudio.com/visual-cpp-build-tools](url)

where visual studio can be freely installed.

**Comment by hagberg** [comment]
See https://github.com/pygraphviz/pygraphviz/issues/103#issuecomment-258568238
